{{- if .Values.ohm.tilerCacheSeedGlobal.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-tiler-cache-seed-global
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-cache-seed-global
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .Values.ohm.tilerCacheSeedGlobal.schedule }}
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.ohm.tilerCacheSeedGlobal.nodeSelector.enabled }}
          nodeSelector:
            {{ .Values.ohm.tilerCacheSeedGlobal.nodeSelector.label_key }}: {{ .Values.ohm.tilerCacheSeedGlobal.nodeSelector.label_value }}
          {{- end }}
          containers:
            - name: {{ .Release.Name }}-tiler-cache-seed-global
              image: {{ .Values.ohm.tilerCacheSeedGlobal.image.name }}:{{ .Values.ohm.tilerCacheSeedGlobal.image.tag }}
              command:
                - python3
                - /app/seed_cache.py
              {{- if .Values.ohm.tilerCacheSeedGlobal.resources.enabled }}
              resources:
                requests:
                  memory: {{ .Values.ohm.tilerCacheSeedGlobal.resources.requests.memory }}
                  cpu: {{ .Values.ohm.tilerCacheSeedGlobal.resources.requests.cpu }}
                limits:
                  memory: {{ .Values.ohm.tilerCacheSeedGlobal.resources.limits.memory }}
                  cpu: {{ .Values.ohm.tilerCacheSeedGlobal.resources.limits.cpu }}
              {{- end }}
              env:
                - name: SEED_MAX_ZOOM
                  value: {{ .Values.ohm.tilerCacheSeedGlobal.env.MAX_ZOOM | quote }}
                - name: SEED_CONCURRENCY
                  value: {{ .Values.ohm.tilerCacheSeedGlobal.env.CONCURRENCY | quote }}
                - name: SEED_NGINX_URL
                  value: {{ .Values.ohm.tilerCacheSeedGlobal.env.NGINX_URL | quote }}
                - name: SEED_GROUPS
                  value: {{ .Values.ohm.tilerCacheSeedGlobal.env.GROUPS | quote }}
          restartPolicy: OnFailure
      backoffLimit: 3
{{- end }}
