services:
  ohmx_adiff_producion:
    image: rub21/ohmx-adiff:v6
    container_name: ohmx_adiff_producion
    environment:
      - API_URL=https://api.openhistoricalmap.org
      - PLANET_PBF_URL=https://s3.amazonaws.com/planet.openhistoricalmap.org/planet/planet-250807_0102.osm.pbf
      - MINUTE_REPLICATION_URL=https://planet.openhistoricalmap.org/?prefix=replication/minute/
      - OSMX_INITIAL_SEQNUM=1683000
      - AWS_S3_BUCKET=planet.openhistoricalmap.org
    env_file:
      - .env.ohmx_adiff
    volumes:
      - ohmx_db:/data
volumes:
  ohmx_db:
    driver: local
    name: ohmx_db_production
