osm-seed:
  environment: dev
  cloudProvider: aws
  AWS_S3_BUCKET: s3://osmseed-dev
  AWS_SSL_ARN: {{AWS_SSL_ARN}}
  serviceType: ClusterIP
  createClusterIssuer: false

  domain: staging.openhistoricalmap.org

  adminEmail: admin@openhistoricalmap.org

  db:
    enabled: false

  web:
    enabled: false

  memcached:
    enabled: false

  planetDump:
    enabled: false

  fullHistory:
    enabled: false

  replicationJob:
    enabled: false

  populateApidb:
    enabled: false

  osmProcessor:
    enabled: false

  dbBackupRestore:
    cronjobs:
      - name: web-db
        enabled: false

  tilerDb:
    enabled: false

  tilerImposm:
    enabled: false
  tilerServer:
    enabled: false

  tilerServerCacheCleaner:
    enabled: false

  # ====================================================================================================
  # Variables for Tasking Manager DB
  # ====================================================================================================
  tmDb:
    enabled: true
    image:
      name: "postgis/postgis"
      tag: "14-3.3"
    nodeSelector:
      enabled: true
      label_key: nodegroup_type
      label_value: web_medium
    env:
      POSTGRES_DB: tm
      POSTGRES_PASSWORD: {{DEVELOPMENT_TM_DB_PASSWORD}}
      POSTGRES_USER: postgres
    persistenceDisk:
      enabled: true
      accessMode: ReadWriteOnce
      mountPath: /var/lib/postgresql/data
      subPath: postgresql-d
      AWS_ElasticBlockStore_volumeID: vol-0c470f0ea2e7456ea
      AWS_ElasticBlockStore_size: 20Gi
    resources:
      enabled: false
      requests:
        memory: "1Gi"
        cpu: "2"
      limits:
        memory: "2Gi"
        cpu: "2"
  # ====================================================================================================
  # Variables for Tasking Manager API
  # ====================================================================================================

  tmApi:
    enabled: true
    nodeSelector:
      enabled: true
      label_key: nodegroup_type
      label_value: web_medium
    replicaCount: 1
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    ingressDomain: tm-api.development.staging.openhistoricalmap.org
    env:
      TM_ORG_NAME: OpenHistoricalMap
      TM_ORG_CODE: OHM
      TM_ORG_URL: staging.openhistoricalmap.org
      TM_ORG_PRIVACY_POLICY_URL: staging.openhistoricalmap.org/copyright
      TM_ORG_GITHUB: github.com/openhistoricalmap
      OSM_SERVER_URL: https://staging.openhistoricalmap.org
      OSM_NOMINATIM_SERVER_URL: https://nominatim-api.staging.openhistoricalmap.org
      OSM_REGISTER_URL: https://staging.openhistoricalmap.org/user/new
      ID_EDITOR_URL: https://staging.openhistoricalmap.org/edit?editor=id
      POTLATCH2_EDITOR_URL: https://staging.openhistoricalmap.org/edit?editor=potlatch2
      TM_SECRET: {{DEVELOPMENT_TM_API_SECRET}}
      # TM_CONSUMER_KEY: {{STAGING_TM_API_CONSUMER_KEY}}
      # TM_CONSUMER_SECRET: {{STAGING_TM_API_CONSUMER_SECRET}}
      TM_EMAIL_FROM_ADDRESS: web@noreply.openhistoricalmap.org
      TM_EMAIL_CONTACT_ADDRESS: admin@openhistoricalmap.org
      TM_SMTP_HOST: email-smtp.us-east-1.amazonaws.com
      TM_SMTP_PORT: 25
      TM_SMTP_USER: {{MAILER_USERNAME}}
      TM_SMTP_PASSWORD: {{MAILER_PASSWORD}}
      TM_DEFAULT_LOCALE: en
      TM_APP_API_URL: https://tm-api.development.staging.openhistoricalmap.org
      TM_APP_BASE_URL: https://tm-dev-web.staging.openhistoricalmap.org
      TM_IMPORT_MAX_FILESIZE: 3000000
      TM_MAX_AOI_AREA: 15000
      TM_CLIENT_ID: fcskO6_EJa_Je4wBBzM59kJexhOtVbzMxNgmcVOUH-c
      TM_CLIENT_SECRET: 6qy8iNojubeY1wc3QEmUpLwLKcMOORjRy17za4x3f8g

      TM_DEFAULT_CHANGESET_COMMENT: staging
      TM_REDIRECT_URI: https://tm-dev-web.staging.openhistoricalmap.org/authorized
      TM_SCOPE: "read_prefs write_api"
      TM_APP_API_VERSION: v4
      # Add extra info
      TM_ORG_FB: https://www.facebook.com//OpenHistoricalMap
      TM_ORG_INSTAGRAM: https://www.instagram.com/OpenHistoricalMap
      TM_ORG_TWITTER: http://twitter.com/OpenHistoricalMap
      TM_ORG_YOUTUBE: https://www.youtube.com/OpenHistoricalMap
    resources:
      enabled: false
      requests:
        memory: 1Gi
        cpu: "2"
      limits:
        memory: 2Gi
        cpu: "2"

  nominatimApi:
    enabled: false
  overpassApi:
    enabled: false
  taginfo:
    enabled: false
  osmSimpleMetrics:
    enabled: false
  monitoringReplication:
    enabled: false
  changesetReplicationJob:
    enabled: false
  osmchaWeb:
    enabled: false
  osmchaApi:
    enabled: false
    image:
  osmchaDb:
    enabled: false
  planetFiles:
    enabled: false
  adiffService:
    enabled: false
ohm:
  tilerCache:
    enabled: false
  tilerCachePurge:
    enabled: false
  tilerCacheSeedGlobal:
    enabled: false
  tilerCacheSeedCoverage:
    enabled: false
