{{- if .Values.nominatim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-data
  labels:
    {{- include "ohm.serviceLabels" (dict "ctx" . "name" "nominatim") | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.nominatim.persistence.size }}
{{- end }}
