{{- if and .Values.nominatim.enabled .Values.nominatim.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: nominatim
  labels:
    {{- include "ohm.serviceLabels" (dict "ctx" . "name" "nominatim") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nominatim
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
{{- if and .Values.nominatim.enabled .Values.nominatim.ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: nominatim-ui
  labels:
    {{- include "ohm.serviceLabels" (dict "ctx" . "name" "nominatim-ui") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nominatim-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
