services:
  tiler_db:
    container_name: tiler_db
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes: !overwrite
      - tiler_pgdata:/var/lib/postgresql/data
      - ./config/postgresql.production.conf:/etc/postgresql/postgresql.conf
    ports:
      - "54329:5432"
    env_file:
      - .env.tiler
    mem_limit: 100G
    cpus: "30.0"
    shm_size: 16g
    networks:
      - ohm_network

  tiler_imposm:
    container_name: tiler_imposm
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.3347.h9440d7a7
    volumes:
      - tiler_imposm_data:/mnt/data
    env_file:
      - .env.tiler
    command:
      - sh
      - -c
      - |
        while true; do
          # make sure you disable this for importing the data, for update it shule b eenable
          ./liveness.sh || exit 1
          sleep 60
        done &
        ./start.sh
    restart: always
    networks:
      - ohm_network

  # Tiler server
  tiler_server:
    container_name: tiler_server
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.3292.h0f5e7d60
    # ports:
    #   - "9090:9090"
    restart: always
    networks:
      - ohm_network

  tiler_sqs_cleaner:
    container_name: tiler_sqs_cleaner
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.3290.h63549fc1
    environment:
      - PORT=8000
    env_file:
      - .env.tiler
    command:
      - /bin/sh
      - -c
      - |
        set -x
        python sqs_processor.py &
        python main.py
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      - ohm_network

  tiler_s3_cleaner:
    container_name: tiler_s3_cleaner
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.3290.h63549fc1
    # image: tiler-cache:latest
    # build:
    #   context: ../../images/tiler-cache
    #   dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        tiler-cache-cleaner clean_by_prefix --prefix-path-file mnt/data/ohm
        tiler-cache-cleaner clean_by_prefix --prefix-path-file mnt/data/ohm_admin
        tiler-cache-cleaner clean_by_prefix --prefix-path-file mnt/data/ohm_other_boundaries
    env_file:
      - .env.tiler
    networks:
      - ohm_network

  tile_global_seeding:
    container_name: tiler_global_seeding
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.3296.h0e45d176
    env_file:
      - .env.tiler
    volumes:
      - ./seed.sh:/opt/seed.sh
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        /opt/seed.sh global
    networks:
      - ohm_network

  tile_coverage_seeding:
    container_name: tiler_coverage_seeding
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.3296.h0e45d176
    volumes:
      - ./seed.sh:/opt/seed.sh
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        /opt/seed.sh coverage
    env_file:
      - .env.tiler
    networks:
      - ohm_network

  tiler_monitor:
    container_name: tiler_monitor
    image: ghcr.io/openhistoricalmap/tiler-monitor:0.0.1-0.dev.git.3340.h7261c0e9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ../../images/tiler-monitor:/app
      - ../../hetzner:/app/hetzner
      - tiler_monitor_data:/data
    environment:
      - DOCKER_CONFIG_ENVIRONMENT=production
    stdin_open: true
    tty: true
    env_file:
      - .env.tiler
    networks:
      - ohm_network
      
volumes:
  tiler_pgdata:
    driver: local
    name: tiler_db_17_03
  tiler_imposm_data:
    driver: local
    name: tiler_imposm_17_03
  tiler_monitor_data:
    driver: local
    name: tiler_monitor_data_v3

networks:
  ohm_network:
    external: true
    