services:
  tiler_db:
    container_name: tiler_db
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes: !overwrite
      - tiler_pgdata:/var/lib/postgresql/data
      - ./config/postgresql.production.conf:/etc/postgresql/postgresql.conf
    ports:
      - "54329:5432"
    env_file:
      - .env.tiler
    mem_limit: 100G
    cpus: "30.0"
    shm_size: 16g
    networks:
      - ohm_network

  tiler_imposm:
    container_name: tiler_imposm
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.3356.h880c9a8b
    volumes:
      - tiler_imposm_data:/mnt/data
    env_file:
      - .env.tiler
    command:
      - sh
      - -c
      - |
        while true; do
          # make sure you disable this for importing the data
          sleep 600
          ./liveness.sh || exit 1
        done &
        ./start.sh
    restart: always
    networks:
      - ohm_network

  tiler_sqs_cleaner:
    container_name: tiler_sqs_cleaner
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.3290.h63549fc1
    environment:
      - PORT=8000
    env_file:
      - .env.tiler
    command:
      - /bin/sh
      - -c
      - |
        set -x
        python sqs_processor.py &
        python main.py
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      - ohm_network



  tiler_monitor:
    container_name: tiler_monitor
    image: ghcr.io/openhistoricalmap/tiler-monitor:0.0.1-0.dev.git.3348.h4fbb83d8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ../../images/tiler-monitor:/app
      - ../../hetzner:/app/hetzner
      - tiler_monitor_data:/data
    environment:
      - DOCKER_CONFIG_ENVIRONMENT=production
    stdin_open: true
    tty: true
    env_file:
      - .env.tiler
    networks:
      - ohm_network

  tiler_server_martin:
    container_name: tiler_server_martin
    image: ghcr.io/openhistoricalmap/tiler-server-martin:0.0.1-0.dev.git.3357.he67b0015
    restart: always
    environment:
      - OHM_DOMAIN=${OHM_DOMAIN:-openhistoricalmap.org}
    env_file:
      - .env.tiler
    ports:
      - "3030:80"
    volumes:
      - tiler_martin_nginx_cache:/var/cache/nginx
    networks:
      - ohm_network
      

volumes:
  tiler_pgdata:
    driver: local
    name: tiler_db_1704
  tiler_imposm_data:
    driver: local
    name: tiler_imposm_1704
  tiler_monitor_data:
    driver: local
    name: tiler_monitor_1704
  tiler_martin_nginx_cache:
    driver: local
    name: tiler_martin_nginx_cache_1704
networks:
  ohm_network:
    external: true
    