services:
  tiler_server:
    container_name: tiler_server
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.3225.h2122f3e
    # image: tiler-server:staging
    # build:
    #   context: ../../images/tiler-server
    #   dockerfile: Dockerfile
    # ports:
    #   - "9090:9090"
    env_file:
      - .env.tiler
    restart: always
    # volumes:
    #   - ../../images/tiler-server/start.sh:/app/start.sh:ro
    networks:
      - ohm_network

volumes:
  tiler_pgdata:
    driver: local
    name: tiler_db_11_02
  tiler_imposm_data:
    driver: local
    name: tiler_imposm_11_02
      
networks:
  ohm_network:
    external: true
    