services:
  tiler_db:
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    volumes: !overwrite
      - tiler_pgdata:/var/lib/postgresql/data
      - ./config/postgresql.production.conf:/etc/postgresql/postgresql.conf
    ports:
      - "54329:5432"
    mem_limit: 55G
    cpus: "28.0"

  tiler_imposm:
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.3208.h6ef73bb
    volumes:
      - tiler_imposm_data:/mnt/data
    command:
      - sh
      - -c
      - |
        while true; do
          # make sure you disable this for importing the data, for update it shule b eenable
          ./liveness.sh || exit 1
          sleep 60
        done &
        ./start.sh
    restart: always
    networks:
      - ohm_network

  # Tiler server
  tiler_server:
    container_name: tiler_server
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.3225.h2122f3e
    ports:
      - "9090:9090"
    restart: always
    networks:
      - ohm_network

  tiler_sqs_cleaner:
    container_name: tiler_sqs_cleaner
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.3245.hffaf924
    environment:
      - PORT=8000
    env_file:
      - .env.tiler
    command:
      - /bin/sh
      - -c
      - |
        set -x
        python sqs_processor.py &
        python main.py
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      - ohm_network

  tiler_s3_cleaner:
    container_name: tiler_s3_cleaner
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.3245.hffaf924
    env_file:
      - .env.tiler
    networks:
      - ohm_network

  tile_global_seeding:
    container_name: tiler_global_seeding
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.3225.h2122f3e
    env_file:
      - .env.tiler
    volumes:
      - ./seed.sh:/opt/seed.sh
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        /opt/seed.sh global
    networks:
      - ohm_network

  tile_coverage_seeding:
    container_name: tiler_coverage_seeding
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.3225.h2122f3e
    volumes:
      - ./seed.sh:/opt/seed.sh
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        /opt/seed.sh coverage
    env_file:
      - .env.tiler
    networks:
      - ohm_network

  tiler_monitor:
    container_name: tiler_monitor
    image: ghcr.io/openhistoricalmap/tiler-monitor:0.0.1-0.dev.git.2874.ha9bff68
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../images/tiler-monitor:/app
      - ../../hetzner:/app/hetzner
    environment:
      - DOCKER_CONFIG_ENVIRONMENT=production
    stdin_open: true
    tty: true
    env_file:
      - .env.tiler
    networks:
      - ohm_network
      
volumes:
  tiler_pgdata:
    driver: local
    name: tiler_db_11_02
  tiler_imposm_data:
    driver: local
    name: tiler_imposm_11_02

networks:
  ohm_network:
    external: true
    