services:
  db_staging:
    container_name: tiler_db_staging
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    volumes:
      - tiler_staging_pgdata:/var/lib/postgresql/data
      - ./config/postgresql.staging.conf:/etc/postgresql/postgresql.conf
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_CONFIG_FILE=/etc/postgresql/postgresql.conf
    command:
      - postgres
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "54321:5432"
    env_file:
      - .env.staging
    networks:
      - ohm_network

  imposm_staging:
    container_name: tiler_imposm_staging
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.3040.ha5561ae
    volumes:
      - tiler_staging_imposmdata:/mnt/data
    command:
      - sh
      - -c
      - |
        ./start.sh
    env_file:
      - .env.staging
    restart: always
    networks:
      - ohm_network


  tiler_server_staging:
    container_name: tiler_server_staging
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.3043.h18ca5aa
    ports:
      - "9091:9090"
    env_file:
      - .env.staging
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
    volumes:
      - /staging/ohm-deploy/images/tiler-server/start.sh:/app/start.sh
    networks:
      - ohm_network

  tiler_sqs_cleaner_production:
    container_name: tiler_sqs_cleaner_production
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.3027.hb928b7e
    env_file:
      - .env.production
    restart: always
    environment:
      - PORT=8000
    command:
      - /bin/sh
      - -c
      - |
        python sqs_processor.py &
        SQS_PID=$!
        # Monitor sqs_processor - if it dies, kill main.py to trigger container restart
        (while kill -0 $SQS_PID 2>/dev/null; do sleep 10; done; echo "sqs_processor.py exited, terminating container"; pkill -f "python main.py"; exit 1) &
        python main.py
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; r=urllib.request.urlopen('http://localhost:8000/health'); exit(0) if r.getcode()==200 else exit(1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ohm_network
      

  tiler_s3_cleaner_staging:
    container_name: tiler_s3_cleaner_staging
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2846.h88a0cab
    env_file:
      - .env.staging
    networks:
      - ohm_network

  tiler_monitor_staging:
    container_name: tiler_monitor_staging
    image: ghcr.io/openhistoricalmap/tiler-monitor:0.0.1-0.dev.git.2706.h1b7db88
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../images/tiler-monitor:/app
      - ../hetzner:/app/hetzner
    environment:
      - DOCKER_CONFIG_ENVIRONMENT=staging
    env_file:
      - .env.staging
    stdin_open: true
    tty: true
    networks:
      - ohm_network

volumes:
  tiler_staging_pgdata:
    driver: local
    name: tiler_db_04_11
  tiler_staging_imposmdata:
    driver: local
    name: tiler_imposm_04_11

networks:
  ohm_network:
    external: true
    