{{- if .Values.overpass.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: overpass
  labels:
    {{- include "ohm.serviceLabels" (dict "ctx" . "name" "overpass") | nindent 4 }}
spec:
  serviceName: overpass
  replicas: {{ .Values.overpass.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: overpass
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "ohm.serviceLabels" (dict "ctx" . "name" "overpass") | nindent 8 }}
    spec:
      containers:
        - name: overpass
          image: "{{ .Values.overpass.image.repository | default "ghcr.io/openhistoricalmap/overpass-api" }}:{{ .Values.overpass.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            {{- range $k, $v := .Values.overpass.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- if .Values.overpass.resources.enabled }}
          resources:
            requests:
              {{- toYaml .Values.overpass.resources.requests | nindent 14 }}
            limits:
              {{- toYaml .Values.overpass.resources.limits | nindent 14 }}
          {{- end }}
          volumeMounts:
            - name: db
              mountPath: {{ .Values.overpass.persistence.mountPath }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          # Long startup window. Overpass init may take hours.
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
            failureThreshold: 360
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: overpass-db
{{- end }}
