{{- if .Values.osmcha.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osmcha-db
  labels:
    {{- include "ohm.serviceLabels" (dict "ctx" . "name" "osmcha-db") | nindent 4 }}
spec:
  serviceName: osmcha-db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: osmcha-db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "ohm.serviceLabels" (dict "ctx" . "name" "osmcha-db") | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.osmcha.db.image.repository }}:{{ .Values.osmcha.db.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: osmcha-env
          {{- if .Values.osmcha.db.resources.enabled }}
          resources:
            requests:
              {{- toYaml .Values.osmcha.db.resources.requests | nindent 14 }}
            limits:
              {{- toYaml .Values.osmcha.db.resources.limits | nindent 14 }}
          {{- end }}
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: [pg_isready]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: osmcha-db
---
apiVersion: v1
kind: Service
metadata:
  name: osmcha-db
  labels:
    {{- include "ohm.serviceLabels" (dict "ctx" . "name" "osmcha-db") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: osmcha-db
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
