{{- if .Values.osmcha.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osmcha-db
  labels:
    {{- include "ohm.serviceLabels" (dict "ctx" . "name" "osmcha-db") | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.osmcha.db.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osmcha-staticfiles
  labels:
    {{- include "ohm.serviceLabels" (dict "ctx" . "name" "osmcha") | nindent 4 }}
spec:
  accessModes: [ReadWriteMany]
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: 5Gi
{{- end }}
