apiVersion: v2
name: ohm-services
version: 0.1.0
appVersion: "0.1.0"
description: OpenHistoricalMap secondary services (taginfo, overpass, nominatim, osmcha, tiler) for Kubernetes
home: https://github.com/OpenHistoricalMap/ohm-deploy
sources:
  - https://github.com/OpenHistoricalMap/ohm-deploy
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: OpenHistoricalMap
    url: https://www.openhistoricalmap.org
