[[providers.layers]]
name = "admin_boundaries_centroid_z0_2"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry,  
    ABS(osm_id) AS osm_id, 
    NULLIF(admin_level, '') AS admin_level, 
    NULLIF(name, '') AS name, 
    NULLIF(type, '') AS type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z0_2
WHERE 
    has_label = 0 
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z3_5"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    NULLIF(admin_level, '') AS admin_level, 
    NULLIF(name, '') AS name, 
    NULLIF(type, '') AS type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z3_5
WHERE 
    has_label = 0 
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z6_7"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    NULLIF(admin_level, '') AS admin_level, 
    NULLIF(name, '') AS name, 
    NULLIF(type, '') AS type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z6_7
WHERE 
    has_label = 0 
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z8_9"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    NULLIF(admin_level, '') AS admin_level, 
    NULLIF(name, '') AS name, 
    NULLIF(type, '') AS type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z8_9
WHERE 
    has_label = 0 
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z10_12"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    NULLIF(admin_level, '') AS admin_level, 
    NULLIF(name, '') AS name, 
    NULLIF(type, '') AS type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z10_12
WHERE 
    has_label = 0 
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z13_15"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    NULLIF(admin_level, '') AS admin_level, 
    NULLIF(name, '') AS name, 
    NULLIF(type, '') AS type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z13_15
WHERE 
    has_label = 0 
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z16_20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    NULLIF(admin_level, '') AS admin_level, 
    NULLIF(name, '') AS name, 
    NULLIF(type, '') AS type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z16_20
WHERE 
    has_label = 0 
    AND geometry && !BBOX!
"""
