[[maps.layers]]
name = "land_ohm_maritime"
provider_layer = "osm.admin_boundaries_maritime_0-2"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "land_ohm_maritime"
provider_layer = "osm.admin_boundaries_maritime_3-5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "land_ohm_maritime"
provider_layer = "osm.admin_boundaries_maritime_6-7"
min_zoom = 6
max_zoom = 7

[[maps.layers]]
name = "land_ohm_maritime"
provider_layer = "osm.admin_boundaries_maritime_8-9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "land_ohm_maritime"
provider_layer = "osm.admin_boundaries_maritime_10-20"
min_zoom = 10
max_zoom = 12
