[[providers.layers]]
name = "admin_boundaries_lines_z0_2"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    member as osm_id, 
    admin_level, 
    type,
    maritime,
    dispute,
    indefinite,
    indeterminate, 
    min_start_date_iso AS start_date,
    max_end_date_iso AS end_date,
    min_start_decdate as start_decdate, 
    max_end_decdate as end_decdate
FROM 
    mview_admin_boundaries_lines_merged_z0_2
WHERE 
    geometry && !BBOX!
"""
[[providers.layers]]
name = "admin_boundaries_lines_z3_5"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    member as osm_id, 
    admin_level, 
    type,
    maritime,
    dispute,
    indefinite,
    indeterminate, 
    min_start_date_iso AS start_date,
    max_end_date_iso AS end_date,
    min_start_decdate as start_decdate, 
    max_end_decdate as end_decdate
FROM 
    mview_admin_boundaries_lines_merged_z3_5
WHERE 
    admin_level IN (1,2,3,4) 
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_lines_z6_7"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    member as osm_id, 
    admin_level, 
    type,
    maritime,
    dispute,
    indefinite,
    indeterminate, 
    min_start_date_iso AS start_date,
    max_end_date_iso AS end_date,
    min_start_decdate as start_decdate, 
    max_end_decdate as end_decdate
FROM 
    mview_admin_boundaries_lines_merged_z6_7
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_lines_z8_9"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    member as osm_id, 
    admin_level, 
    type,
    maritime,
    dispute,
    indefinite,
    indeterminate, 
    min_start_date_iso AS start_date,
    max_end_date_iso AS end_date,
    min_start_decdate as start_decdate, 
    max_end_decdate as end_decdate
FROM 
    mview_admin_boundaries_lines_merged_z8_9
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_lines_z10_12"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    member as osm_id, 
    admin_level, 
    type,
    maritime,
    dispute,
    indefinite,
    indeterminate, 
    min_start_date_iso AS start_date,
    max_end_date_iso AS end_date,
    min_start_decdate as start_decdate, 
    max_end_decdate as end_decdate
FROM 
    mview_admin_boundaries_lines_merged_z10_12 
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_lines_z13_15"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    member as osm_id, 
    admin_level, 
    type,
    maritime,
    dispute,
    indefinite,
    indeterminate, 
    min_start_date_iso AS start_date,
    max_end_date_iso AS end_date,
    min_start_decdate as start_decdate, 
    max_end_decdate as end_decdate
FROM 
    mview_admin_boundaries_lines_merged_z13_15 
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_lines_z16_20"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    member as osm_id, 
    admin_level, 
    type,
    maritime,
    dispute,
    indefinite,
    indeterminate, 
    min_start_date_iso AS start_date,
    max_end_date_iso AS end_date,
    min_start_decdate as start_decdate, 
    max_end_decdate as end_decdate
FROM 
    mview_admin_boundaries_lines_merged_z16_20
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z0_2"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z3_5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z6_7"
min_zoom = 6
max_zoom = 7

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z8_9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z10_12"
min_zoom = 10
max_zoom = 12

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z13_15"
min_zoom = 13
max_zoom = 15

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z16_20"
min_zoom = 16
max_zoom = 20
