[[providers.layers]]
name = "admin_boundaries_centroid_z0_2"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry,  
    ABS(osm_id) AS osm_id, 
    admin_level, 
    name, 
    type, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z0_2
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z3_5"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    admin_level, 
    name, 
    type, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z3_5
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z6_7"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    admin_level, 
    name, 
    type, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z6_7
WHERE 
    admin_level IN (1,2,3,4,5,6)
    AND has_label = 0 
    AND name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z8_9"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    admin_level, 
    name, 
    type, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z8_9
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z10_12"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    admin_level, 
    name, 
    type, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z10_12
WHERE 
    geometry && !BBOX!
"""


[[providers.layers]]
name = "admin_boundaries_centroid_z13_15"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    admin_level, 
    name, 
    type, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z13_15
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z16_20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    admin_level, 
    name, 
    type, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_admin_boundaries_centroid_z16_20
WHERE 
    geometry && !BBOX!
"""