[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z0_2"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z3_5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z6_7"
min_zoom = 6
max_zoom = 7

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z8_9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z10_12"
min_zoom = 10
max_zoom = 12

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z13_15"
min_zoom = 13
max_zoom = 15

[[maps.layers]]
name = "land_ohm_lines"
provider_layer = "osm.admin_boundaries_lines_z16_20"
min_zoom = 16
max_zoom = 20
