[[providers.layers]]
name = "admin_boundaries_centroid_z0_2"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry,  
    id, 
    admin_level,
    name, 
    type, 
    start_date, 
    end_date, 
    area_km2, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_admin_boundaries_centroids_z0_2
WHERE geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z3_5"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    admin_level,
    name, 
    type, 
    start_date, 
    end_date, 
    area_km2, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_admin_boundaries_centroids_z3_5
WHERE geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z6_7"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    admin_level,
    name, 
    type, 
    start_date, 
    end_date, 
    area_km2, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_admin_boundaries_centroids_z6_7
WHERE geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z8_9"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    admin_level,
    name, 
    type, 
    start_date, 
    end_date, 
    area_km2, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_admin_boundaries_centroids_z8_9
WHERE geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z10_12"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    admin_level,
    name, 
    type, 
    start_date, 
    end_date, 
    area_km2, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_admin_boundaries_centroids_z10_12
WHERE geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z13_15"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    admin_level,
    name, 
    type, 
    start_date, 
    end_date, 
    area_km2, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_admin_boundaries_centroids_z13_15
WHERE geometry && !BBOX!
"""

[[providers.layers]]
name = "admin_boundaries_centroid_z16_20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    admin_level,
    name, 
    type, 
    start_date, 
    end_date, 
    area_km2, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_admin_boundaries_centroids_z16_20
WHERE geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroid_z0_2"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroid_z3_5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroid_z6_7"
min_zoom = 6
max_zoom = 7

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroid_z8_9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroid_z10_12"
min_zoom = 10
max_zoom = 12

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroid_z13_15"
min_zoom = 13
max_zoom = 15

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroid_z16_20"
min_zoom = 16
max_zoom = 20
