## Boundaries lines from admin_level=1,2, zoom 0-2 and geometry simplification=500
[[providers.layers]]
name = "admin_boundaries_lines_0-2"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Simplify(ST_Boundary(geometry), 500), !BBOX!) AS geometry, 
    id, 
    osm_id, 
    admin_level, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_admin_areas 
WHERE 
    admin_level IN (1,2) 
    AND geometry && !BBOX!
"""

## Boundaries lines from admin_level=1,2,3,4, zoom 3-5 and geometry simplification=200
[[providers.layers]]
name = "admin_boundaries_lines_3-5"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Simplify(ST_Boundary(geometry), 200), !BBOX!) AS geometry, 
    id, 
    osm_id, 
    admin_level, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_admin_areas 
WHERE 
    admin_level IN (1,2,3,4) 
    AND geometry && !BBOX!
"""

## Boundaries lines from admin_level=1,2,3,4,5,6 , zoom 6-7 and geometry simplification=100
[[providers.layers]]
name = "admin_boundaries_lines_6-7"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Simplify(ST_Boundary(geometry), 100), !BBOX!) AS geometry, 
    id, 
    osm_id, 
    admin_level, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_admin_areas 
WHERE 
    admin_level IN (1,2,3,4,5,6) 
    AND geometry && !BBOX!
"""

## Boundaries lines from admin_level=1,2,3,4,5,6,7,8,9 , zoom 8-9 and geometry simplification=50
[[providers.layers]]
name = "admin_boundaries_lines_8-9"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Simplify(ST_Boundary(geometry), 50), !BBOX!) AS geometry, 
    id, 
    osm_id, 
    admin_level, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_admin_areas 
WHERE 
    admin_level IN (1,2,3,4,5,6,7,8,9) 
    AND geometry && !BBOX!
"""

## Boundaries lines from admin_level=1,2,3,4,5,6,7,8,9,10 , zoom 10-12 and geometry simplification=20
[[providers.layers]]
name = "admin_boundaries_lines_10-12"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Simplify(ST_Boundary(geometry), 20), !BBOX!) AS geometry, 
    id, 
    osm_id, 
    admin_level, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_admin_areas 
WHERE 
    admin_level IN (1,2,3,4,5,6,7,8,9,10) 
    AND geometry && !BBOX!
"""

## Boundaries lines from admin_level=1,2,3,4,5,6,7,8,9,10 , zoom 13-15 and geometry simplification=5
[[providers.layers]]
name = "admin_boundaries_lines_13-15"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Simplify(ST_Boundary(geometry), 5), !BBOX!) AS geometry, 
    id, 
    osm_id, 
    admin_level, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_admin_areas 
WHERE 
    admin_level IN (1,2,3,4,5,6,7,8,9,10) 
    AND geometry && !BBOX!
"""

## Boundaries lines from admin_level=1,2,3,4,5,6,7,8,9,10 , zoom 16-20
[[providers.layers]]
name = "admin_boundaries_lines_16-20"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Boundary(geometry), !BBOX!) AS geometry, 
    id, 
    osm_id, 
    admin_level, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_admin_areas 
WHERE 
    admin_level IN (1,2,3,4,5,6,7,8,9,10) 
    AND geometry && !BBOX!
"""
