
[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroids_0-2"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroids_3-5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroids_6-7"
min_zoom = 6
max_zoom = 7

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroids_8-9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "land_ohm_centroids"
provider_layer = "osm.admin_boundaries_centroids_10-20"
min_zoom = 10
max_zoom = 20