# Layer configuration for amenity points
[[providers.layers]]
name = "amenity_points"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_amenity_points 
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "amenity_points"
provider_layer = "osm.amenity_points"
min_zoom = 14
max_zoom = 20
