[[providers.layers]]
name = "amenity_areas"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name, 
    type, 
    start_date, 
    end_date, 
    area,  
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_amenity_areas_z14_20
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "amenity_areas"
provider_layer = "osm.amenity_areas"
min_zoom = 14
max_zoom = 20
