# Layer configuration for amenity areas
[[providers.layers]]
name = "amenity_areas"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_amenity_areas 
WHERE 
    geometry && !BBOX!
"""
---
[[maps.layers]]
name = "amenity_areas"
provider_layer = "osm.amenity_areas"
min_zoom = 14
max_zoom = 20
