# Layer configuration for buildings
[[providers.layers]]
name = "buildings"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings 
WHERE 
    geometry && !BBOX!
"""
---
[[maps.layers]]
name = "buildings"
provider_layer = "osm.buildings"
min_zoom = 14
max_zoom = 20
