# Layer configuration for buildings
[[providers.layers]]
name = "buildings_14"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 1200
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_15"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 1000
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_16"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 800
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_17"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 600
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""


[[providers.layers]]
name = "buildings_18"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 500
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_19"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 400
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings 
WHERE 
    name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""
#######Maps
# Buildings
[[maps.layers]]
name = "buildings_centroids"
provider_layer = "osm.buildings_14"
min_zoom = 14
max_zoom = 14

[[maps.layers]]
name = "buildings_centroids"
provider_layer = "osm.buildings_15"
min_zoom = 15
max_zoom = 15

[[maps.layers]]
name = "buildings_centroids"
provider_layer = "osm.buildings_16"
min_zoom = 16
max_zoom = 16

[[maps.layers]]
name = "buildings_centroids"
provider_layer = "osm.buildings_17"
min_zoom = 17
max_zoom = 17

[[maps.layers]]
name = "buildings_centroids"
provider_layer = "osm.buildings_18"
min_zoom = 18
max_zoom = 18

[[maps.layers]]
name = "buildings_centroids"
provider_layer = "osm.buildings_19"
min_zoom = 19
max_zoom = 19

[[maps.layers]]
name = "buildings_centroids"
provider_layer = "osm.buildings_20"
min_zoom = 20
max_zoom = 20
