# Layer configuration for buildings
[[providers.layers]]
name = "buildings_14"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 1200
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_15"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 1000
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_16"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 800
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_17"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 600
    AND geometry && !BBOX!
"""


[[providers.layers]]
name = "buildings_18"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 500
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_19"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_buildings 
WHERE 
    ST_Area(geometry) > 400
    AND geometry && !BBOX!
"""

[[providers.layers]]
name = "buildings_20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    nullif(as_numeric(height), -1) AS height, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_buildings 
WHERE 
    geometry && !BBOX!
"""
