[[providers.layers]]
name = "buildings_points"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_buildings_points_named
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "buildings_points"
provider_layer = "osm.buildings_points"
min_zoom = 14
max_zoom = 20
