[[providers.layers]]
name = "communication_z14_15"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry,
    osm_id,
    name,
    type,
    start_date,
    end_date,
    start_decdate,
    end_decdate,
    communication_telephone,
    communication_telegraph,
    communication_internet,
    communication_cable_television,
    communication_television,
    communication_radio,
    communication_microwave,
    communication_bos,
    communication_mobile_phone,
    communication_satellite,
    communication_amateur_radio,
    communication_optical,
    communication_space,
    communication_gsm_r,
    telecom,
    operator,
    location,
    layer,
    {{LENGUAGES}}
FROM
    mv_communication_z14_15
WHERE
    geometry && !BBOX!
"""

[[providers.layers]]
name = "communication_z16_20"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry,
    osm_id,
    name,
    type,
    start_date,
    end_date,
    start_decdate,
    end_decdate,
    communication_telephone,
    communication_telegraph,
    communication_internet,
    communication_cable_television,
    communication_television,
    communication_radio,
    communication_microwave,
    communication_bos,
    communication_mobile_phone,
    communication_satellite,
    communication_amateur_radio,
    communication_optical,
    communication_space,
    communication_gsm_r,
    telecom,
    operator,
    location,
    layer,
    {{LENGUAGES}}
FROM
    mv_communication_z16_20
WHERE
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "communication"
provider_layer = "ohm.communication_z14_15"
min_zoom = 14
max_zoom = 15

[[maps.layers]]
name = "communication"
provider_layer = "ohm.communication_z16_20"
min_zoom = 16
max_zoom = 20
