[[providers.layers]]
name = "landuse_areas_gen0_centroids_3-5"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    class, 
    type, 
    area, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_landuse_areas_gen0 
WHERE 
    type IN ('forest', 'wood', 'nature reserve', 'nature_reserve', 'military') 
    AND area > 50000000 
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""

# Layer 1,000,000
[[providers.layers]]
name = "landuse_areas_gen0_centroids_6-9"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    class, 
    type, 
    area, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_landuse_areas_gen0 
WHERE 
    type IN ('forest', 'wood', 'nature reserve', 'nature_reserve', 'military') 
    AND area > 1000000 
    AND name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""

# Layer configuration for landuse areas gen1
[[providers.layers]]
name = "landuse_areas_gen1_centroids_10-12"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    class, 
    type, 
    area, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_landuse_areas_gen1 
WHERE 
    name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""
# Layer configuration for landuse areas
[[providers.layers]]
name = "landuse_areas_centroids_13-20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    tags->'wetland' AS wetland, 
    area, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_landuse_areas 
WHERE 
    name IS NOT NULL
    AND name <> '' 
    AND geometry && !BBOX!
"""
---
[[maps.layers]]
name = "landuse_areas_centroids"
provider_layer = "osm.landuse_areas_gen0_centroids_3-5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "landuse_areas_centroids"
provider_layer = "osm.landuse_areas_gen0_centroids_6-9"
min_zoom = 6
max_zoom = 9

[[maps.layers]]
name = "landuse_areas_centroids"
provider_layer = "osm.landuse_areas_gen1_centroids_10-12"
min_zoom = 10
max_zoom = 12

[[maps.layers]]
name = "landuse_areas_centroids"
provider_layer = "osm.landuse_areas_centroids_13-20"
min_zoom = 13
max_zoom = 20
