# Layer configuration for other lines
[[providers.layers]]
name = "other_lines"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_other_lines 
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "other_lines"
provider_layer = "osm.other_lines"
min_zoom = 14
max_zoom = 20
