# Layer configuration for other areas with a filter
[[providers.layers]]
name = "other_areas_filter"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_other_areas 
WHERE 
    area > 1000000 
    AND geometry && !BBOX!
"""

# Layer configuration for other areas
[[providers.layers]]
name = "other_areas"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_other_areas 
WHERE 
    geometry && !BBOX!
"""
