# Layer configuration for other areas with a filter
[[providers.layers]]
name = "other_areas_centroids_6-8"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_other_areas 
WHERE 
    area > 1000000
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""

# Layer configuration for other areas
[[providers.layers]]
name = "other_areas_centroids_9-11"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_other_areas 
WHERE 
    area > 100000
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""


# Layer configuration for other areas
[[providers.layers]]
name = "other_areas_centroids_12-14"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_other_areas 
WHERE 
    area > 10000
    AND name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""


# Layer configuration for other areas
[[providers.layers]]
name = "other_areas_centroids_15-20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_other_areas 
WHERE 
    name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "other_areas_centroids"
provider_layer = "osm.other_areas_centroids_6-8"
min_zoom = 6
max_zoom = 8

[[maps.layers]]
name = "other_areas_centroids"
provider_layer = "osm.other_areas_centroids_9-11"
min_zoom = 9
max_zoom = 11

[[maps.layers]]
name = "other_areas_centroids"
provider_layer = "osm.other_areas_centroids_12-14"
min_zoom = 12
max_zoom = 14

[[maps.layers]]
name = "other_areas_centroids"
provider_layer = "osm.other_areas_centroids_15-20"
min_zoom = 15
max_zoom = 20
