[[providers.layers]]
name = "other_areas_z14_20"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    area,
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_other_areas_z14_20 
WHERE 
    geometry && !BBOX!
"""
#######Maps

[[maps.layers]]
name = "other_areas"
provider_layer = "osm.other_areas_z14_20"
min_zoom = 14
max_zoom = 20
