[[providers.layers]]
name = "other_lines"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    NULLIF(name, '') AS name,
    class, 
    type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    mv_other_lines_z14_20 
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "other_lines"
provider_layer = "osm.other_lines"
min_zoom = 14
max_zoom = 20
