[[providers.layers]]
name = "other_areas_z14_20"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name, 
    class, 
    type, 
    area,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_other_areas_z14_20 
WHERE 
    geometry && !BBOX!
"""
#######Maps

[[maps.layers]]
name = "other_areas"
provider_layer = "osm.other_areas_z14_20"
min_zoom = 14
max_zoom = 20
