[[providers.layers]]
name = "other_lines"
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    class, 
    type, 
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}}
FROM 
    mv_other_lines_z14_20 
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "other_lines"
provider_layer = "osm.other_lines"
min_zoom = 14
max_zoom = 20
