# Layer configuration for other points
[[providers.layers]]
name = "other_points"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    class, 
    type, 
    tags->'artwork_type' AS artwork_type, 
    tags->'site_type' AS site_type, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_other_points 
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "other_points"
provider_layer = "osm.other_points"
min_zoom = 14
max_zoom = 20
