[[providers.layers]]
name = "place_points_0_2"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name,
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate, 
    tags->'capital' AS capital,
    {{LENGUAGES}}
FROM 
    osm_place_points
WHERE 
    --type IN ('country') 
    type IN (
    'ocean',
    'sea',
    'archipelago',
    'country',
    'territory',
    'unorganized territory'
    ) 
    AND geometry && !BBOX!
"""

    
[[providers.layers]]
name = "place_points_3_5"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name,
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate, 
    tags->'capital' AS capital,
    {{LENGUAGES}}
FROM 
    osm_place_points
WHERE 
    --type IN ('country', 'state', 'territory') 
    type IN (
    'ocean',
    'sea',
    'archipelago',
    'country',
    'territory',
    'unorganized territory',
    'state',
    'province',
    'region'
    ) 
    AND geometry && !BBOX!
"""


[[providers.layers]]
name = "place_points_6_10"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name,
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate, 
    tags->'capital' AS capital,
    {{LENGUAGES}}
FROM 
    osm_place_points
WHERE 
    --type IN ('country', 'state', 'territory', 'city', 'town') 
    type IN (
    'ocean',
    'sea',
    'archipelago',
    'country',
    'territory',
    'unorganized territory',
    'state',
    'province',
    'region',
    'county',
    'municipality',
    'city',
    'town'
    ) 
    AND geometry && !BBOX!
"""


[[providers.layers]]
name = "place_points_11_20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name,
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate, 
    tags->'capital' AS capital,
    {{LENGUAGES}}
FROM 
    osm_place_points
WHERE 
    --type IN ('country', 'state', 'territory', 'city', 'town', 'village', 'suburb', 'locality', 'hamlet', 'islet', 'neighbourhood') 
    geometry && !BBOX!
"""
---
[[maps.layers]]
name = "place_points"
provider_layer = "osm.place_points_0_2"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "place_points"
provider_layer = "osm.place_points_3_5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "place_points"
provider_layer = "osm.place_points_6_10"
min_zoom = 6
max_zoom = 10

[[maps.layers]]
name = "place_points"
provider_layer = "osm.place_points_11_20"
min_zoom = 11
max_zoom = 20
