# Layer configuration for place points
[[providers.layers]]
name = "place_points"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name,
    type, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate, 
    tags->'capital' AS capital,
    {{LENGUAGES}}
FROM 
    osm_place_points
WHERE 
    geometry && !BBOX!
"""
