[[providers.layers]]
name = "place_points_centroids_z0_2"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    type, 
    area_m2, 
    capital,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate, 
    {{LENGUAGES}}
FROM 
    mv_place_points_centroids_z0_2
WHERE 
    geometry && !BBOX!
"""

    
[[providers.layers]]
name = "place_points_centroids_z3_5"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    type, 
    area_m2, 
    capital,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate, 
    {{LENGUAGES}}
FROM 
    mv_place_points_centroids_z3_5
WHERE 
    geometry && !BBOX!
"""


[[providers.layers]]
name = "place_points_centroids_z6_10"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    type, 
    area_m2, 
    capital,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate, 
    {{LENGUAGES}}
FROM 
    mv_place_points_centroids_z6_10
WHERE 
    geometry && !BBOX!
"""


[[providers.layers]]
name = "place_points_centroids_z11_20"
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    type, 
    area_m2, 
    capital,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate, 
    {{LENGUAGES}}
FROM 
    mv_place_points_centroids_z11_20
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "place_points_centroids"
provider_layer = "osm.place_points_centroids_z3_5"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "place_points_centroids"
provider_layer = "osm.place_points_centroids_z3_5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "place_points_centroids"
provider_layer = "osm.place_points_centroids_z6_10"
min_zoom = 6
max_zoom = 10

[[maps.layers]]
name = "place_points_centroids"
provider_layer = "osm.place_points_centroids_z11_20"
min_zoom = 11
max_zoom = 20
