[[providers.layers]]
name = "route_lines_5_9"
geometry_fieldname = "geometry"
geometry_type = "LineString"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Simplify(ST_Boundary(geometry), 50), !BBOX!) AS geometry, 
    r.id,
    r.name,
    r.type,
    r.tags->'ref' AS ref,
    r.tags->'network' AS network,
    r.start_date,
    r.end_date,
    CASE 
        WHEN is_date_valid(r.start_date) THEN isodatetodecimaldate(pad_date(r.start_date, 'start')) 
        ELSE NULL 
    END AS start_decdate,
    CASE 
        WHEN is_date_valid(r.end_date) THEN isodatetodecimaldate(pad_date(r.end_date, 'end')) 
        ELSE NULL 
    END AS end_decdate
FROM osm_relations r
JOIN osm_relation_members m ON r.osm_id = m.osm_id
WHERE r.type = 'route'
AND geometry && !BBOX!
"""

[[providers.layers]]
name = "route_lines_10_15"
geometry_fieldname = "geometry"
geometry_type = "LineString"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(ST_Simplify(ST_Boundary(geometry), 20), !BBOX!) AS geometry, 
    r.id,
    r.name,
    r.type,
    r.tags->'ref' AS ref,
    r.tags->'network' AS network,
    r.start_date,
    r.end_date,
    CASE 
        WHEN is_date_valid(r.start_date) THEN isodatetodecimaldate(pad_date(r.start_date, 'start')) 
        ELSE NULL 
    END AS start_decdate,
    CASE 
        WHEN is_date_valid(r.end_date) THEN isodatetodecimaldate(pad_date(r.end_date, 'end')) 
        ELSE NULL 
    END AS end_decdate
FROM osm_relations r
JOIN osm_relation_members m ON r.osm_id = m.osm_id
WHERE r.type = 'route'
AND geometry && !BBOX!
"""

[[providers.layers]]
name = "route_lines_16_20"
geometry_fieldname = "geometry"
geometry_type = "LineString"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry,!BBOX!) AS geometry,
    r.id,
    r.name,
    r.type,
    r.tags->'ref' AS ref,
    r.tags->'network' AS network,
    r.start_date,
    r.end_date,
    CASE 
        WHEN is_date_valid(r.start_date) THEN isodatetodecimaldate(pad_date(r.start_date, 'start')) 
        ELSE NULL 
    END AS start_decdate,
    CASE 
        WHEN is_date_valid(r.end_date) THEN isodatetodecimaldate(pad_date(r.end_date, 'end')) 
        ELSE NULL 
    END AS end_decdate
FROM osm_relations r
JOIN osm_relation_members m ON r.osm_id = m.osm_id
WHERE r.type = 'route'
AND geometry && !BBOX!
"""
