[[providers.layers]]
name = "routes_lines"
geometry_fieldname = "geometry"
geometry_type = "LineString"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry,
    ABS(osm_id) AS osm_id,
    name,
    type,
    route,
    ref,
    network,
    direction,
    operator,
    state,
    symbol,
    distance,
    roundtrip,
    interval,
    duration,
    tourism,
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM osm_relation_members_routes
WHERE geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "route_lines"
provider_layer = "osm.routes_lines"
min_zoom = 5
max_zoom = 20
