[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z5"
min_zoom = 5
max_zoom = 5

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z6"
min_zoom = 6
max_zoom = 6

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z7"
min_zoom = 7
max_zoom = 7

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z8"
min_zoom = 8
max_zoom = 10

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z9"
min_zoom = 9
max_zoom = 9

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z10"
min_zoom = 10
max_zoom = 10

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z11"
min_zoom = 11
max_zoom = 11

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z12"
min_zoom = 12
max_zoom = 12

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z13_15"
min_zoom = 13
max_zoom = 15

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z16_20"
min_zoom = 16
max_zoom = 20
