[[providers.layers]]
name = "transport_areas"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "osm_id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    NULLIF(name, '') AS name, 
    class, 
    type, 
    area, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    mv_transport_areas_z12_20 
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "transport_areas"
provider_layer = "osm.transport_areas"
min_zoom = 12
max_zoom = 20
