[[providers.layers]]
name = "transport_lines_5_10_relation"
geometry_fieldname = "geometry"
geometry_type = "LineString"
id_fieldname = "id"
sql = """
SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry,
    r.id,
    r.name,
    r.tags->'ref' AS ref,
    r.tags->'class' AS class,
    r.tags->'highway' AS type,
    r.tags->'route' AS route,
    r.tags->'tunnel' AS tunnel,
    r.tags->'bridge' AS bridge,
    r.tags->'usage' AS usage,
    r.tags->'electrified' AS electrified,
    r.tags->'highspeed' AS highspeed,
    tags->'start_date' AS start_date,
    tags->'end_date' AS end_date,
    isodatetodecimaldate(pad_date(r.tags->'start_date', 'start')) AS start_decdate,
    isodatetodecimaldate(pad_date(r.tags->'end_date', 'end')) AS end_decdate
FROM osm_relations r, osm_relation_members m
WHERE r.osm_id=m.osm_id
AND r.type IN ('multilinestring', 'route')
AND geometry && !BBOX!
"""

[[providers.layers]]
name = "transport_lines_11_20_relation"
geometry_fieldname = "geometry"
geometry_type = "LineString"
id_fieldname = "id"
sql = """
SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry,
    r.id,
    r.name,
    r.tags->'ref' AS ref,
    r.tags->'class' AS class,
    r.tags->'highway' AS type,
    r.tags->'route' AS route,
    r.tags->'tunnel' AS tunnel,
    r.tags->'bridge' AS bridge,
    r.tags->'access' AS access,
    r.tags->'service' AS service,
    r.tags->'ford' AS ford,
    r.tags->'construction' AS construction,
    r.tags->'usage' AS usage,
    r.tags->'electrified' AS electrified,
    r.tags->'highspeed' AS highspeed,
    tags->'start_date' AS start_date,
    tags->'end_date' AS end_date,
    m.name AS mname,
    isodatetodecimaldate(pad_date(r.tags->'start_date', 'start')) AS start_decdate,
    isodatetodecimaldate(pad_date(r.tags->'end_date', 'end')) AS end_decdate
FROM osm_relations r, osm_relation_members m
WHERE r.osm_id=m.osm_id
AND r.type IN ('multilinestring', 'route')
AND geometry && !BBOX!
"""
