# Layer configuration for transport associated streets
[[providers.layers]]
name = "transport_associated_streets"
geometry_fieldname = "geometry"
geometry_type = "LineString"
id_fieldname = "id"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    r.id, 
    m.member, 
    r.osm_id, 
    m.name, 
    m.relname, 
    m.index, 
    r.type, 
    r.tags->'start_date' AS start_date, 
    r.tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(r.tags->'start_date', 'start')) AS start_decdate, 
    isodatetodecimaldate(pad_date(r.tags->'end_date', 'end')) AS end_decdate,
    {{LENGUAGES_RELATION}}
FROM 
    osm_relations r, 
    osm_relation_members m 
WHERE 
    r.osm_id = m.osm_id 
    AND r.type = 'associatedStreet' 
    AND geometry && !BBOX!
"""
---
[[maps.layers]]
name = "transport_associated_streets"
provider_layer = "osm.transport_associated_streets"
min_zoom = 7
max_zoom = 20
