[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z5_7"
min_zoom = 5
max_zoom = 7

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z8_9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z10_11"
min_zoom = 10
max_zoom = 11

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z12_13"
min_zoom = 12
max_zoom = 13

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_z14_20"
min_zoom = 14
max_zoom = 20
