[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_gen_5"
min_zoom = 5
max_zoom = 5

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_gen_6"
min_zoom = 6
max_zoom = 6

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_gen_7"
min_zoom = 7
max_zoom = 7

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_gen_8-10"
min_zoom = 8
max_zoom = 10

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_gen_11"
min_zoom = 11
max_zoom = 11

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_gen_12-13"
min_zoom = 12
max_zoom = 13

[[maps.layers]]
name = "transport_lines"
provider_layer = "osm.transport_lines_gen_14-24"
min_zoom = 14
max_zoom = 24
