[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_centroid_z0_2"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    mview_water_areas_centroid_z0_2
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_centroid_z3_5"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    mview_water_areas_centroid_z3_5 
WHERE 
    geometry && !BBOX!
"""

# Water bodies > 1,000,000 sqm
[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_centroid_z6_7"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    mview_water_areas_centroid_z6_7
WHERE 
    geometry && !BBOX!
"""

# Water bodies > 10,000 sqm
[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_centroid_z8_9"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    mview_water_areas_centroid_z8_9 
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_centroid_z10_12"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    mview_water_areas_centroid_z10_12
WHERE 
    name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_centroid_z13_15"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    NULLIF(start_date, '') AS start_date, 
    NULLIF(end_date, '') AS end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    mview_water_areas_centroid_z13_15 
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "water_areas_centroids"
provider_layer = "osm.water_areas_centroid_z0_2"
min_zoom = 0
max_zoom = 2

[[maps.layers]]
name = "water_areas_centroids"
provider_layer = "osm.water_areas_centroid_z3_5"
min_zoom = 3
max_zoom = 5

[[maps.layers]]
name = "water_areas_centroids"
provider_layer = "osm.water_areas_centroid_z6_7"
min_zoom = 6
max_zoom = 7

[[maps.layers]]
name = "water_areas_centroids"
provider_layer = "osm.water_areas_centroid_z8_9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "water_areas_centroids"
provider_layer = "osm.water_areas_centroid_z10_12"
min_zoom = 10
max_zoom = 12

[[maps.layers]]
name = "water_areas_centroids"
provider_layer = "osm.water_areas_centroid_z13_15"
min_zoom = 13
max_zoom = 20
