[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_zoom_0_2_centroid"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_water_areas_zoom_0_2
WHERE 
    name IS NOT NULL
    AND name <> ''
    AND geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_zoom_3_5_centroid"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_water_areas_zoom_3_5 
WHERE 
    name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""

# Water bodies > 1,000,000 sqm
[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_zoom_6_7_centroid"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_water_areas_zoom_6_7
WHERE 
    name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""

# Water bodies > 10,000 sqm
[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_zoom_8_9_centroid"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_water_areas_zoom_8_9 
WHERE 
    name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_zoom_10_12_centroid"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_water_areas_zoom_10_12
WHERE 
    name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_zoom_13_15_centroid"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_water_areas_zoom_13_15 
WHERE 
    name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "point"
id_fieldname = "osm_id"
name = "water_areas_16_20_centroid"
sql = """
SELECT 
    ST_AsMVTGeom((ST_MaximumInscribedCircle(geometry)).center, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    area, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}}
FROM 
    osm_water_areas_16_20
WHERE 
    name IS NOT NULL 
    AND name <> '' 
    AND geometry && !BBOX!
"""
