[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "id"
name = "water_lines"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    id, 
    osm_id, 
    name, 
    type, 
    tags->'bridge' AS bridge, 
    tags->'surface' AS surface, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_water_lines 
WHERE 
    type IN ('river', 'canal', 'stream', 'ditch', 'drain', 'dam', 'cliff') 
    AND geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_gen0"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    tags->'bridge' AS bridge, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_water_lines_gen0 
WHERE 
    type IN ('river', 'canal') 
    AND geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_gen1"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    tags->'bridge' AS bridge, 
    tags->'surface' AS surface, 
    tags->'start_date' AS start_date, 
    tags->'end_date' AS end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate 
FROM 
    osm_water_lines_gen1 
WHERE 
    type IN ('river', 'canal', 'stream', 'ditch', 'drain', 'dam', 'cliff') 
    AND geometry && !BBOX!
"""
