[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_z8_9"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    type, 
    NULLIF(bridge, '') AS bridge,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_water_lines_z8_9 
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_z10_12"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    type, 
    NULLIF(bridge, '') AS bridge,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_water_lines_z10_12
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_z13_15"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    type, 
    NULLIF(bridge, '') AS bridge,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_water_lines_z13_15
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_z16_20"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    osm_id, 
    name,
    type, 
    NULLIF(bridge, '') AS bridge,
    start_date, 
    end_date, 
    start_decdate, 
    end_decdate,
    {{LENGUAGES}} 
FROM 
    mv_water_lines_z16_20 
WHERE 
    geometry && !BBOX!
"""
#######Maps
[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_z8_9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_z10_12"
min_zoom = 10
max_zoom = 12

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_z13_15"
min_zoom = 13
max_zoom = 15

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_z16_20"
min_zoom = 16
max_zoom = 20
