[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_gen0_8-10"
min_zoom = 8
max_zoom = 10

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_gen0_11"
min_zoom = 11
max_zoom = 11

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_gen0_12-14"
min_zoom = 12
max_zoom = 14

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_gen0_15-24"
min_zoom = 15
max_zoom = 24

