[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_z8_9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_z10_12"
min_zoom = 10
max_zoom = 12

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_z13_15"
min_zoom = 13
max_zoom = 15

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_z16_20"
min_zoom = 16
max_zoom = 20


