[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_zoom_8_9"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    bridge, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_water_lines_zoom_8_9 
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_zoom_10_11"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    bridge, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(start_date, 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(end_date, 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_water_lines_zoom_10_11
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_zoom_12_14"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    bridge, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_water_lines_zoom_12_14
WHERE 
    geometry && !BBOX!
"""

[[providers.layers]]
geometry_fieldname = "geometry"
geometry_type = "linestring"
id_fieldname = "osm_id"
name = "water_lines_zoom_15_20"
sql = """
SELECT 
    ST_AsMVTGeom(geometry, !BBOX!) AS geometry, 
    ABS(osm_id) AS osm_id, 
    name, 
    type, 
    bridge, 
    start_date, 
    end_date, 
    isodatetodecimaldate(pad_date(tags->'start_date', 'start'), FALSE) AS start_decdate, 
    isodatetodecimaldate(pad_date(tags->'end_date', 'end'), FALSE) AS end_decdate,
    {{LENGUAGES}} 
FROM 
    osm_water_lines_zoom_15_20 
WHERE 
    geometry && !BBOX!
"""
