[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_gen0_8-9"
min_zoom = 8
max_zoom = 9

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_gen1_10-11"
min_zoom = 10
max_zoom = 11

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_12-14"
min_zoom = 12
max_zoom = 14

[[maps.layers]]
name = "water_lines"
provider_layer = "osm.water_lines_15-20"
min_zoom = 15
max_zoom = 20
