{{- if .Values.ohm.tilerCachePurge.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tiler-cache-sqs
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-cache-sqs-deployment
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-tiler-cache-sqs
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-tiler-cache-sqs
    spec:
      serviceAccountName: job-service-account
      containers:
        - name: {{ .Chart.Name }}tiler-cache-sqs
          image: "{{ .Values.ohm.tilerCache.image.name }}:{{ .Values.ohm.tilerCache.image.tag }}"
          command:
            - sh
            - -c
            - |
              set -x
              python sqs_processor.py
          env:
            - name: REGION_NAME
              value: {{ .Values.ohm.tilerCachePurge.env.REGION_NAME | quote }}
            - name: ENVIRONMENT
              value: {{ .Release.Name | quote }}
            - name: SQS_QUEUE_URL
              value: {{  .Values.ohm.tilerCachePurge.env.SQS_QUEUE_URL | quote }}
            - name: DOCKER_IMAGE
              value: {{ .Values.ohm.tilerCachePurge.env.DOCKER_IMAGE | quote }}
            - name: NODEGROUP_TYPE
              value: {{ .Values.ohm.tilerCachePurge.env.NODEGROUP_TYPE | quote }}
            - name: MAX_ACTIVE_JOBS
              value: {{ .Values.ohm.tilerCachePurge.env.MAX_ACTIVE_JOBS | quote }}
            - name: DELETE_OLD_JOBS_AGE
              value: {{ .Values.ohm.tilerCachePurge.env.DELETE_OLD_JOBS_AGE | quote }}
            # execution parameters
            - name: EXECUTE_PURGE
              value: {{ .Values.ohm.tilerCachePurge.env.EXECUTE_PURGE | quote }}
            - name: EXECUTE_SEED
              value: {{ .Values.ohm.tilerCachePurge.env.EXECUTE_SEED | quote }}
            # zoom
            - name: PURGE_MIN_ZOOM
              value: {{ .Values.ohm.tilerCachePurge.env.PURGE_MIN_ZOOM | quote }}
            - name: PURGE_MAX_ZOOM
              value: {{ .Values.ohm.tilerCachePurge.env.PURGE_MAX_ZOOM | quote }}
            - name: SEED_MIN_ZOOM
              value: {{ .Values.ohm.tilerCachePurge.env.SEED_MIN_ZOOM | quote }}
            - name: SEED_MAX_ZOOM
              value: {{ .Values.ohm.tilerCachePurge.env.SEED_MAX_ZOOM | quote }}
            # concurrency
            - name: SEED_CONCURRENCY
              value: {{ .Values.ohm.tilerCachePurge.env.SEED_CONCURRENCY | quote }}
            - name: PURGE_CONCURRENCY
              value: {{ .Values.ohm.tilerCachePurge.env.PURGE_CONCURRENCY | quote }}
            - name: ZOOM_LEVELS_TO_DELETE
              value: {{ .Values.ohm.tilerCachePurge.env.ZOOM_LEVELS_TO_DELETE | quote }}
            - name: S3_BUCKET_CACHE_TILER
              value: {{ .Values.ohm.tilerCachePurge.env.S3_BUCKET_CACHE_TILER | quote }}
            - name: S3_BUCKET_PATH_FILES
              value: {{ .Values.ohm.tilerCachePurge.env.S3_BUCKET_PATH_FILES | quote }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-tiler-server-cm
          - configMapRef:
              name: {{ .Release.Name }}-tiler-db-cm
          {{- if .Values.ohm.tilerCachePurge.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.ohm.tilerCachePurge.resources.requests.memory }}
              cpu: {{ .Values.ohm.tilerCachePurge.resources.requests.cpu }}
            limits:
              memory: {{ .Values.ohm.tilerCachePurge.resources.limits.memory }}
              cpu: {{ .Values.ohm.tilerCachePurge.resources.limits.cpu }}
          {{- end }}
      {{- if .Values.ohm.tilerCachePurge.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.ohm.tilerCachePurge.nodeSelector.label_key }} : {{ .Values.ohm.tilerCachePurge.nodeSelector.label_value }}
      {{- end }}
{{- end }}