osm-seed:
  db:
    image:
      name: chartpress_replace_me
      tag: chartpress_replace_me
  web:
    image:
      name: chartpress_replace_me
      tag: chartpress_replace_me
  tilerDb:
    image:
      name: chartpress_replace_me
      tag: chartpress_replace_me
  tilerImposm:
    image:
      name: chartpress_replace_me
      tag: chartpress_replace_me
  tilerServer:
    image:
      name: chartpress_replace_me
      tag: chartpress_replace_me
  tmApi:
    image:
      name: chartpress_replace_me
      tag: chartpress_replace_me
  cgimap:
    image:
      name: chartpress_replace_me
      tag: chartpress_replace_me
ohm:
  tilerCache:
    image:
      name: chartpress_replace_me
      tag: chartpress_replace_me
