services:

  taginfo_data:
    container_name: taginfo_data
    image: ghcr.io/osm-seed/taginfo:0.1.0-0.dev.git.984.hb289ff1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/data/production/taginfo_data:/usr/src/app/data
      - ${HOME}/data/production/taginfo_data_planet:/osm/planet/var
    environment:
      - AWS_S3_BUCKET=planet.openhistoricalmap.org
      - DOCKER_CONFIG_ENVIRONMENT=production
    command:
      - /bin/bash
      - -lc
      - |
        set -ex
        while true; do
          rm -rf /usr/src/app/data/*
          /usr/src/app/start.sh
          sleep 259200
        done
    env_file:
      - ./.env.taginfo
    networks:
      - ohm_network
      