services:
  taginfo_web:
    container_name: taginfo_web
    image:  ghcr.io/osm-seed/taginfo-web:0.1.0-0.dev.git.983.h32750c8
    volumes:
      -  ${HOME}/data/staging/taginfo_data:/usr/src/app/data
    env_file:
      - ./.env.taginfo
    restart: always
    networks:
      - ohm_network

networks:
  ohm_network:
    external: true