services:
  taginfo_web:
    volumes:
      - ${HOME}/data/production/taginfo_data_proceced:/usr/src/app/data

  taginfo_data:
    container_name: taginfo_data
    image: ghcr.io/osm-seed/taginfo:0.1.0-0.dev.git.984.hb289ff1
    volumes:
      - ${HOME}/data/production/taginfo_data:/usr/src/app/data
      - ${HOME}/data/production/taginfo_data_planet:/osm/planet/var
    environment:
      - AWS_S3_BUCKET=planet.openhistoricalmap.org
    command:
      - /bin/bash
      - -lc
      - |
        set -ex
        # Run every 3 days at 3:00 AM
        /usr/src/app/start.sh 
        echo "0 3 1-31/3 * * /usr/src/app/start.sh >> /var/log/taginfo-cron.log 2>&1" > /tmp/cron_logs
        crontab /tmp/cron_logs
        touch /var/log/taginfo-cron.log
        cron -f
    networks:
      - ohm_network