services:
  taginfo_web:
    container_name: taginfo_web
    image:  ghcr.io/osm-seed/taginfo-web:0.1.0-0.dev.git.986.h0fae372
    env_file:
      - ./.env.taginfo
    restart: always
    networks:
      - ohm_network

networks:
  ohm_network:
    external: true