services:
  taginfo_data:
    container_name: taginfo_data_staging
    image: ghcr.io/osm-seed/taginfo:0.1.0-0.dev.git.984.hb289ff1
    volumes:
      - ${HOME}/data/staging/taginfo_data:/usr/src/app/data
      - ${HOME}/data/staging/taginfo_data_planet:/osm/planet/var
      - ${HOME}/.aws:/root/.aws:ro
    env_file:
      - ./.env.sample
    restart: always
    networks:
      - ohm_network

  taginfo_web:
    container_name: taginfo_web_staging
    image:  ghcr.io/osm-seed/taginfo-web:0.1.0-0.dev.git.983.h32750c8
    env_file:
      - ./.env.sample
    restart: always
    networks:
      - ohm_network
    volumes:
      - ${HOME}/data/staging/taginfo_data:/usr/src/app/data
      - ${HOME}/data/staging/taginfo_data_planet:/osm/planet/var
networks:
  ohm_network:
    external: true
