services:
  ohmx-adiff:
    image: rub21/ohmx-adiff:v6
    container_name: ohmx-adiff
    restart: unless-stopped
    build:
      context: ../images/ohmx-adiff-builder
      dockerfile: Dockerfile
    environment:
      - API_URL=https://api.openhistoricalmap.org
      - PLANET_PBF_URL=https://s3.amazonaws.com/planet.openhistoricalmap.org/planet/planet-250807_0102.osm.pbf
      - MINUTE_REPLICATION_URL=https://planet.openhistoricalmap.org/?prefix=replication/minute/
      - OSMX_INITIAL_SEQNUM=1683000
      - AWS_S3_BUCKET=planet.openhistoricalmap.org
      - HEARTBEAT_DIR=/tmp/heartbeat
      - HEARTBEAT_STALE_SECONDS=600
    env_file:
      - ../envs/.env.ohmx_addif
    volumes:
      - ohmx_db:/data
      - ./../images/ohmx-adiff-builder/start.sh:/app/start.sh
      - ./../images/ohmx-adiff-builder/healthcheck.sh:/app/healthcheck.sh
      - ./../images/ohmx-adiff-builder/utils:/app/utils
      - ./../../osmx-adiff-builder/:/app
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 60s
      timeout: 10s
      start_period: 600s
      retries: 3
volumes:
  ohmx_db:
    driver: local
    name: ohmx_db
