version: '3.8'
services:
  db:
    image: ohm-tiler-db:v1
    build:
      context: ../images/tiler-db
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - ../data/tiler-db-data:/var/lib/postgresql/data
    env_file:
      - ../envs/.env.tiler
    restart: always
  imposm:
    image: ohm-tiler-imposm:v1
    build:
      context: ../images/tiler-imposm
      dockerfile: Dockerfile
    volumes:
      - ../data/tiler-imposm-data:/mnt/data
      - ../images/tiler-imposm:/app
    command:
      - sh
      - -c
      - "sleep 60 && ./start.sh"
    env_file:
      - ../envs/.env.tiler
  tiler:
    image: ohm-tiler-server:v1
    build:
      context: ../images/tiler-server
      dockerfile: Dockerfile
    volumes:
      - ../data/tiler-server-data:/mnt/data
      - ../images/tiler-server:/app
    ports:
      - "9090:9090"
    env_file:
      - ../envs/.env.tiler
    restart: always
