services:
  tm-api:
    image: ohm/ohm-tm-api:v3
    build:
      context: ../images/tasking-manager-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../envs/.env.tiler
    restart: always
