services:
  tm-api:
    image: rub21/ohm-tm-api:v11
    build:
      context: ../images/tasking-manager-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../envs/.env.tiler
    restart: always
  tm-web:
    image: node:18
    ports:
      - "3000:3000"
    env_file:
      - ../envs/.env.tm
    restart: always
    volumes:
      - ./../../tasking-manager/frontend:/frontend