version: '3.8'
services:
  db:
    platform: linux/amd64
    image: osmseed-db:v1
    build:
      context: ./../images/db
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    env_file:
      - ./../envs/.env.web
  web:
    image: osmseed-web:v1
    build:
      context: ./../images/web
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - ./../envs/.env.web
####### Enable for development mode
# volumes:
#   - ./../../ohm-website:/var/www
