services:
  db:
    platform: linux/amd64
    image: ohm-db:v2
    build:
      context: ./../images/db
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    env_file:
      - ./../envs/.env.web
    restart: always
    networks:
      - web_network
  web:
    image: ohm-web:v1
    build:
      context: ./../images/web
      dockerfile: Dockerfile
    volumes:
      - ./../../ohm-website/:/var/www
      - bundle_data:/usr/local/bundle
      - node_modules_data:/var/www/node_modules
      - ./../images/web/config/settings.yml:/tmp/settings.yml:rw
      - ./../images/web/start.sh:/var/www/start.sh
      - ./../images/web/dev.sh:/var/www/dev.sh
    env_file:
      - ./../envs/.env.web
    ports:
      - '3000:3000'
    networks:
      - web_network
    depends_on:
      - db
      - memcached

  memcached:
    image: memcached:latest
    ports:
      - '11211:11211'
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
volumes:
  bundle_data:
  node_modules_data:
  