version: '3.4'
services:
  tiler-db:
    image: osmseed-tiler-db:v1
    build: 
      context: ./tiler-db
      dockerfile: Dockerfile
    ports:
      -  "5432:5432"
    volumes:
      - ./tiler-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env-tiler
  tiler-imposm:
    image: osmseed-tiler-imposm:v1
    build: 
      context: ./tiler-imposm
      dockerfile: Dockerfile
    volumes:
      - ./tiler-imposm-data-2:/mnt/data
    env_file:
      - ./.env-tiler
    command: >
      /bin/bash -c "./start.sh"
    tiler-server:
      image: osmseed-tiler-server:v1
      build:
        context: ./tiler-server
        dockerfile: Dockerfile
      volumes:
        - ./tiler-server-data:/mnt/data
      ports:
        - "9090:9090"
      command: >
        /bin/bash -c "
        echo Starting tiles server!;
        ./start.sh"
      env_file:
        - ./.env-tiler
    tiler-cache-cleaner:
      image: osmseed-tiler-server:v1
      build:
        context: ./tiler-server
        dockerfile: Dockerfile
      command: >
        /bin/bash -c "
        echo cache cleaner;
        ./tile_cache_downloader.sh & ./expire-watcher.sh"
      env_file:
        - ./.env-tiler