version: '3.4'
services:
  db:
    platform: linux/amd64
    image: osmseed-db:v1
    build:
      context: ../images/db
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - ../data/db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.example
  web:
    image: osmseed-web:v1
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - ./.env.example
  # tiler-db:
  #   image: osmseed-tiler-db:v1
  #   build:
  #     context: ./tiler-db
  #     dockerfile: Dockerfile
  #   ports:
  #     -  "5432:5432"
  #   volumes:
  #     - ./tiler-db-data:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env.example
  # tiler-imposm:
  #   image: osmseed-tiler-imposm:v1
  #   build:
  #     context: ./tiler-imposm
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./tiler-imposm-data-2:/mnt/data
  #   env_file:
  #     - ./.env.example
  #   command: >
  #     /bin/bash -c "./start.sh"
  # tiler-server:
  #   image: osmseed-tiler-server:v1
  #   build:
  #     context: ./tiler-server
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./tiler-server-data:/mnt/data
  #   ports:
  #     - "9090:9090"
  #   command: >
  #     /bin/bash -c "
  #     echo Starting tiles server!;
  #     ./start.sh"
  #   env_file:
  #     - ./.env.example
  # tiler-cache-cleaner:
  #   image: tiler-cache-cleaner:v1
  #   build:
  #     context: ./tiler-server
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./tiler-cache-cleaner-data:/mnt/data
  #   command: >
  #     /bin/bash -c "
  #     echo Starting cache cleaner!;
  #     ./cache_cleaner.sh"
  #   env_file:
  #     - ./.env.example
