services:
  db_staging:
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    volumes:
      - /data/tiler_production_db_28_05_2025:/var/lib/postgresql/data
      - ./config/postgresql.staging.conf:/etc/postgresql/postgresql.conf
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_CONFIG_FILE=/etc/postgresql/postgresql.conf
    command:
      - postgres
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "5433:5432"
    env_file:
      - .env.staging
    networks:
      - tiler_network_staging

  imposm_staging:
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.2621.hd366608
    volumes:
      - /data/tiler_production_imposm_28_05_2025:/mnt/data
    command:
      - sh
      - -c
      - |
        ./start.sh
    env_file:
      - .env.staging
    restart: always
    networks:
      - tiler_network_staging

  tiler_staging:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2622.hf249ec9
    ports:
      - "9091:9090"
    env_file:
      - .env.staging
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
    networks:
      - tiler_network_staging

  tiler_sqs_cleaner_staging:
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2622.hf249ec9
    env_file:
      - .env.staging
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
    networks:
      - tiler_network_staging

  tiler_s3_cleaner_staging:
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2622.hf249ec9
    env_file:
      - .env.production
    networks:
      - tiler_network_staging

networks:
  tiler_network_staging:
    driver: bridge
