services:
  db_staging:
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    volumes:
      - tiler_staging_pgdata:/var/lib/postgresql/data
      - ./config/postgresql.staging.conf:/etc/postgresql/postgresql.conf
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_CONFIG_FILE=/etc/postgresql/postgresql.conf
    command:
      - postgres
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "54321:5432"
    env_file:
      - .env.staging
    networks:
      - tiler_network_staging

  imposm_staging:
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.2632.h717d2ec
    volumes:
      - tiler_staging_imposmdata:/mnt/data
    command:
      - sh
      - -c
      - |
        ./start.sh
    env_file:
      - .env.staging
    restart: always
    networks:
      - tiler_network_staging
<<<<<<< HEAD

  tiler_staging:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2630.heaedf31
=======
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G
  tiler:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2591.h83b12a8
>>>>>>> main
    ports:
      - "9091:9090"
    env_file:
      - .env.staging
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
    networks:
      - tiler_network_staging

  tiler_sqs_cleaner_staging:
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2632.h717d2ec
    env_file:
      - .env.staging
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
    networks:
      - tiler_network_staging

<<<<<<< HEAD
  tiler_s3_cleaner_staging:
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2632.h717d2ec
    env_file:
      - .env.staging
=======
  global_seeding:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2591.h83b12a8
    env_file:
      - .env.staging
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        set -x
        while true; do
          pkill -f "tegola" && sleep 5
          echo "0/0/0" > /opt/tile-list.tiles
          tegola cache seed tile-list /opt/tile-list.tiles \
            --config=/opt/tegola_config/config.toml \
            --map=osm \
            --min-zoom=0 \
            --max-zoom=4 \
            --concurrency=32 \
            --overwrite=true
          sleep 3600
        done
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
    networks:
      - tiler_network_staging

  tile_coverage_seeding:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2591.h83b12a8
    env_file:
      - .env.staging
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        set -x
        while true; do
          wget -O tile-list.tiles https://s3.amazonaws.com/planet.openhistoricalmap.org/tile_coverage/tiles.list
          pkill -f "tegola" && sleep 5
          tegola cache seed tile-list tile-list.tiles \
            --config=/opt/tegola_config/config.toml \
            --map=osm \
            --min-zoom=8 \
            --max-zoom=14 \
            --concurrency=32 \
            --overwrite=false
          sleep 3600
        done
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
>>>>>>> main
    networks:
      - tiler_network_staging

networks:
  tiler_network_staging:
    driver: bridge

volumes:
  tiler_staging_pgdata:
    driver: local
    name: tiler_db_11_06_2025
  tiler_staging_imposmdata:
    driver: local
    name: tiler_imposm_11_06_2025
    