services:
  db_production:
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    volumes:
      - /data/tiler_production_db_20250211:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    restart: always
    networks:
      - tiler_network
    deploy:
      resources:
        limits:
          cpus: '28.0'
          memory: 55G
  imposm_production:
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.2179.he1248ec
    volumes:
      - /data/tiler_production_imposm_20250211:/mnt/data
    command:
      - sh
      - -c
      - |
        while true; do
          ./liveness.sh || exit 1
          sleep 60
        done &
        ./start.sh
    env_file:
      - .env.production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
    networks:
      - tiler_network
  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - tiler_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
networks:
  tiler_network:
    driver: bridge
    