services:
  # Tiler db
  db_production:
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    volumes:
      - /data/tiler_production_db_28_05_2025:/var/lib/postgresql/data
      - ./config/postgresql.production.conf:/etc/postgresql/postgresql.conf
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_CONFIG_FILE=/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    restart: always
    networks:
      - tiler_network
    deploy:
      resources:
        limits:
          cpus: '28.0'
          memory: 55G
          
  # imposm3
  imposm_production:
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.2572.h77205fe
    volumes:
      - /data/tiler_production_imposm_28_05_2025:/mnt/data
    command:
      - sh
      - -c
      - |
        while true; do
          ./liveness.sh || exit 1
          sleep 60
        done &
        ./start.sh
    env_file:
      - .env.production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
    networks:
      - tiler_network
  # Tiler server
  tiler_production:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2585.hf4baec4
    ports:
      - "9090:9090"
    env_file:
      - .env.production
    restart: always
    networks:
      - tiler_network
  # Tiler cache
  cache_production:
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2238.h67c76c8
    env_file:
      - .env.production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - tiler_network


  global_seeding_production:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2585.hf4baec4
    env_file:
      - .env.production
    volumes:
      - ./seed.sh:/opt/seed.sh
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        /opt/seed.sh global
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - tiler_network

  tile_coverage_seeding_production:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2585.hf4baec4
    env_file:
      - .env.production
    volumes:
      - ./seed.sh:/opt/seed.sh
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        /opt/seed.sh coverage
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - tiler_network

  remove_cache_tiles_production:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2585.hf4baec4
    env_file:
      - .env.production
    volumes:
      - ./rm_s3.py:/opt/rm_s3.py
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        python3 /opt/rm_s3.py
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - tiler_network

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - tiler_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
networks:
  tiler_network:
    driver: bridge
    