services:
  db_staging:
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    volumes:
      - tiler_staging_pgdata:/var/lib/postgresql/data
      - ./config/postgresql.staging.conf:/etc/postgresql/postgresql.conf
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_CONFIG_FILE=/etc/postgresql/postgresql.conf
    command:
      - postgres
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "54321:5432"
    env_file:
      - .env.staging
    networks:
      - tiler_network_staging

  imposm_staging:
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.2710.h5e17b92
    volumes:
      - tiler_staging_imposmdata:/mnt/data
    command:
      - sh
      - -c
      - |
        ./start.sh
    env_file:
      - .env.staging
    restart: always
    networks:
      - tiler_network_staging

  imposm_mv_staging:
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.2710.h5e17b92
    env_file:
      - .env.staging
    networks:
      - tiler_network_staging

  tiler_staging:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2694.h5468129
    ports:
      - "9091:9090"
    env_file:
      - .env.staging
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
    networks:
      - tiler_network_staging

  tiler_sqs_cleaner_staging:
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2706.h1b7db88
    env_file:
      - .env.staging
    # volumes:
    #   - ../images/tiler-cache:/app
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MiB
    networks:
      - tiler_network_staging

  tiler_s3_cleaner_staging:
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2706.h1b7db88
    env_file:
      - .env.staging
    networks:
      - tiler_network_staging

  tiler_monitor_staging:
    image: ghcr.io/openhistoricalmap/tiler-monitor:0.0.1-0.dev.git.2706.h1b7db88
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../images/tiler-monitor:/app
      - ../hetzner:/app/hetzner
    environment:
      - DOCKER_CONFIG_ENVIRONMENT=staging
    env_file:
      - .env.staging
    stdin_open: true
    tty: true
    networks:
      - tiler_network_staging

networks:
  tiler_network_staging:
    driver: bridge

volumes:
  tiler_staging_pgdata:
    driver: local
    name: tiler_db_29_07_2025_v2
  tiler_staging_imposmdata:
    driver: local
    name: tiler_imposm_29_07_2025_v2
