services:
  # Tiler db
  db_production:
    image: ghcr.io/openhistoricalmap/tiler-db:0.0.1-0.dev.git.2166.hc55c4cd
    volumes:
      - /data/tiler_production_db_20250211:/var/lib/postgresql/data
      - ./config/postgresql.production.conf:/etc/postgresql/postgresql.conf
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_CONFIG_FILE=/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    restart: always
    networks:
      - tiler_network
    deploy:
      resources:
        limits:
          cpus: '28.0'
          memory: 55G
          
  # imposm3
  imposm_production:
    image: ghcr.io/openhistoricalmap/tiler-imposm:0.0.1-0.dev.git.2191.hdcb5877
    volumes:
      - /data/tiler_production_imposm_20250211:/mnt/data
    command:
      - sh
      - -c
      - |
        while true; do
          ./liveness.sh || exit 1
          sleep 60
        done &
        ./start.sh
    env_file:
      - .env.production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
    networks:
      - tiler_network
  # Tiler server
  tiler_production:
      image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2241.hba0f0a5
      ports:
        - "9090:9090"
      env_file:
        - .env.production
      restart: always
      networks:
        - tiler_network
  # Tiler cache
  cache_production:
    image: ghcr.io/openhistoricalmap/tiler-cache:0.0.1-0.dev.git.2238.h67c76c8
    env_file:
      - .env.production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - tiler_network


  global_seeding_production:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2234.hfa6976e
    env_file:
      - .env.production
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        set -x
        while true; do
          pkill -f "tegola" && sleep 5
          echo "0/0/0" > /opt/tile-list.tiles
          tegola cache seed tile-list /opt/tile-list.tiles \
            --config=/opt/tegola_config/config.toml \
            --map=osm \
            --min-zoom=0 \
            --max-zoom=7\
            --concurrency=32 \
            --overwrite=true
          sleep 3600
        done
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - tiler_network

  tile_coverage_seeding_production:
    image: ghcr.io/openhistoricalmap/tiler-server:0.0.1-0.dev.git.2234.hfa6976e
    env_file:
      - .env.production
    entrypoint:
      - /bin/bash
      - "-c"
      - |
        set -x
        while true; do
          wget -O tile-list.tiles https://s3.amazonaws.com/planet.openhistoricalmap.org/tile_coverage/tiles.list
          pkill -f "tegola" && sleep 5
          tegola cache seed tile-list tile-list.tiles \
            --config=/opt/tegola_config/config.toml \
            --map=osm \
            --min-zoom=8 \
            --max-zoom=14 \
            --concurrency=32 \
            --overwrite=false
          sleep 3600
        done
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - tiler_network

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - tiler_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
networks:
  tiler_network:
    driver: bridge
    