[webserver]
port = ":${TILER_SERVER_PORT}"
	[webserver.headers]
	Access-Control-Allow-Origin = "*"

# Tegola offers three tile caching strategies: "file", "redis", and "s3"
[cache]
type = "${TILER_CACHE_TYPE}"
basepath ="${TILER_CACHE_BASEPATH}"
max_zoom = "${TILER_CACHE_MAX_ZOOM}"

bucket = "${TILER_CACHE_BUCKET}"
region = "${TILER_CACHE_REGION}"
aws_access_key_id = "${TILER_CACHE_AWS_ACCESS_KEY_ID}"
aws_secret_access_key = "${TILER_CACHE_AWS_SECRET_ACCESS_KEY}"
endpoint = "${TILER_CACHE_AWS_ENDPOINT}"

# metrics
[observer]
type = "prometheus"

####################################
## OpenHistoricalMap providers
####################################
[[providers]]
name = "osm"
type = "mvt_postgis"
uri = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
max_connections = 150
	###### PROVIDERS_OSM

####################################
## OHM admin boundaries areas
####################################

[[providers]]
name = "ohm_admin"
type = "mvt_postgis"
uri = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
max_connections = 25
	###### PROVIDERS_ADMIN_BOUNDARIES_AREAS

####################################
## Natural Earth (ne) providers
####################################
[[providers]]
name = "ne"
type = "mvt_postgis"
uri = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
max_connections = 25
	###### Water lands ne
	[[providers.layers]]
	name = "ne_water_lakes_0-8"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "id"
	sql = "SELECT ST_AsMVTGeom(wkb_geometry,!BBOX!) AS geometry, name, id FROM mview_ne_lakes WHERE wkb_geometry && !BBOX!"

####################################
## OpenStreetMap land providers
####################################
[[providers]]
name = "osm_land"
type = "mvt_postgis"
uri = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
max_connections = 25
	[[providers.layers]]
	name = "osm_land_0-2"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry, ogc_fid FROM mview_land_z0_2 WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "osm_land_3-5"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry, ogc_fid FROM mview_land_z3_5 WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "osm_land_6-7"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry, ogc_fid FROM mview_land_z6_7 WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "osm_land_8-9"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry, ogc_fid FROM mview_land_z8_9 WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "osm_land_10-12"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry, ogc_fid FROM mview_land_z10_12 WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "osm_land_13-15"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry, ogc_fid FROM mview_land_z13_15 WHERE geometry && !BBOX!"

	[[providers.layers]]
	name = "osm_land_16-20"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsMVTGeom(geometry,!BBOX!) AS geometry, ogc_fid FROM mview_land_z16_20 WHERE geometry && !BBOX!"


####################################
## OpenHistoricalMap maps
####################################
[[maps]]
name = "osm"
attribution = "OpenHistoricalMap"
center = [-42.31214, 70.00455, 10.0]
	###### MAPS_OSM

####################################
## OHM admin boundaries areas maps
####################################
[[maps]]
name = "ohm_admin"
attribution = "OpenHistoricalMap"
center = [0.0, 0.0, 0.0]
	###### MAPS_ADMIN_BOUNDARIES_AREAS

####################################
## Natural Earth maps
####################################
[[maps]]
name = "ne"
attribution = "Natural Earth"
center = [-42.31214, 70.00455, 10.0]
	# Water lakes Natural Earth
	[[maps.layers]]
	name = "water_areas"
	provider_layer = "ne.ne_water_lakes_0-8"
	min_zoom = 0
	max_zoom = 8


####################################
## OpenStreetMap land maps
####################################
[[maps]]
name = "osm_land"
attribution = "OpenStreetMap Land"
center = [-42.31214, 70.00455, 10.0]
	[[maps.layers]]
	name = "land"
	provider_layer = "osm_land.osm_land_0-2"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "land"
	provider_layer = "osm_land.osm_land_3-5"
	min_zoom = 3
	max_zoom = 5

	[[maps.layers]]
	name = "land"
	provider_layer = "osm_land.osm_land_6-7"
	min_zoom = 6
	max_zoom = 7

	[[maps.layers]]
	name = "land"
	provider_layer = "osm_land.osm_land_8-9"
	min_zoom = 8
	max_zoom = 9

	[[maps.layers]]
	name = "land"
	provider_layer = "osm_land.osm_land_10-12"
	min_zoom = 10
	max_zoom = 12

	[[maps.layers]]
	name = "land"
	provider_layer = "osm_land.osm_land_13-15"
	min_zoom = 13
	max_zoom = 15

	[[maps.layers]]
	name = "land"
	provider_layer = "osm_land.osm_land_16-20"
	min_zoom = 16
	max_zoom = 20
