[webserver]
port = ":${TILER_SERVER_PORT}"
	[webserver.headers]
	Access-Control-Allow-Origin = "*"

# Tegola offers three tile caching strategies: "file", "redis", and "s3"
[cache]
type = "${TILER_CACHE_TYPE}"
basepath ="${TILER_CACHE_BASEPATH}"
max_zoom = "${TILER_CACHE_MAX_ZOOM}"

bucket = "${TILER_CACHE_BUCKET}"
region = "${TILER_CACHE_REGION}"
aws_access_key_id = "${TILER_CACHE_AWS_ACCESS_KEY_ID}"
aws_secret_access_key = "${TILER_CACHE_AWS_SECRET_ACCESS_KEY}"
endpoint = "${TILER_CACHE_AWS_ENDPOINT}"

# metrics
[observer]
type = "prometheus"

####################################
## OpenHistoricalMap providers
####################################
[[providers]]
name = "osm"
type = "mvt_postgis"
uri = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
max_connections = 150
	###### PROVIDERS

####################################
## Natural Earth (ne) providers
####################################
[[providers]]
name = "ne"
type = "mvt_postgis"
uri = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
max_connections = 25
	###### Water lands ne
	[[providers.layers]]
	name = "ne_water_lakes_0-8"
	geometry_fieldname = "geometry"
	geometry_type = "multipolygon"
	id_fieldname = "id"
	sql = "SELECT ST_AsMVTGeom(wkb_geometry,!BBOX!) AS geometry, name, id FROM mview_ne_lakes WHERE wkb_geometry && !BBOX!"

####################################
## OpenHistoricalMap maps
####################################
[[maps]]
name = "osm"
attribution = "OpenHistoricalMap"
center = [-74.275329586789, -12.153492567373, 1.0]
	###### MAPS

####################################
## Natural Earth maps
####################################
[[maps]]
name = "ne"
attribution = "Natural Earth"
center = [-74.275329586789, -12.153492567373, 8.0]
	# Water lakes Natural Earth
	[[maps.layers]]
	name = "water_areas"
	provider_layer = "ne.ne_water_lakes_0-8"
	min_zoom = 0
	max_zoom = 8
