server_url: "staging.openhistoricalmap.org"
embed_server_url: "https://embed.openhistoricalmap.org/"
# OAuth application for the web site
oauth_application: "OAUTH_CLIENT_ID"
oauth_key: "OAUTH_KEY"
# OAuth consumer key for iD
id_application: ""
smtp_address: "localhost"
smtp_port: 25
smtp_domain: "localhost"
smtp_enable_starttls_auto: true
smtp_tls_verify_mode: "none"
smtp_authentication: null
smtp_user_name: null
smtp_password: null
