# The server protocol and host
server_protocol: "http"
server_url: "openhistoricalmap.example.com"
status: "online"
# OAuth application for the web site
oauth_application: "OAUTH_CLIENT_ID"
oauth_key: "OAUTH_KEY"
# OAuth consumer key for iD
id_application: ""
# List of memcache servers to use for caching
memcache_servers: []
# URL of Nominatim instance to use for geocoding
nominatim_url: "https://nominatim.openhistoricalmap.org/"
# URL of Overpass instance to use for feature queries
overpass_url: "https://overpass-api.de/api/interpreter"
# SMTP settings for outbound mail
smtp_address: "localhost"
smtp_port: 25
smtp_domain: "localhost"
smtp_enable_starttls_auto: true
smtp_tls_verify_mode: "none"
smtp_authentication: null
smtp_user_name: null
smtp_password: null
doorkeeper_signing_key: |
  -----BEGIN PRIVATE KEY-----
  PRIVATE_KEY
  -----END PRIVATE KEY-----
