server_url: "0.0.0.0:3000"
embed_server_url: "https://embed.openhistoricalmap.org/"
generator: "OpenHistoricalMap server"
copyright_owner: "OpenHistoricalMap and contributors"
attribution_url: "http://www.openhistoricalmap.org/copyright"
support_email: "ohm-admins@googlegroups.com"
email_from: "OpenHistoricalMap <ohm-admins@googlegroups.com>"
email_return_path: "ohm-admins@googlegroups.com"
api_timeout: 600
web_timeout: 600
nominatim_url: "https://nominatim.openhistoricalmap.org/"
# OAuth application for the website
oauth_application: ""
oauth_key: ""
# OAuth consumer key for iD
id_application: ""
imagery_blacklist:
  # Current Google imagery URLs have google or googleapis in the domain
  - ".*\\.google(apis)?\\..*/.*"
  # Blacklist VWorld
  - "http://xdworld\\.vworld\\.kr:8080/.*"
  # Blacklist here
  - ".*\\.here\\.com[/:].*"
# Mastodon url for verification
mastodon_url: "https://mapstodon.space/@ohm"
smtp_authentication: null
smtp_user_name: null
smtp_password: null
