services:
  overpass:
    image: developmentseed/osmseed-overpass-api:0.1.0-0.dev.git.956.h49d677b
    container_name: overpass
    # ports:
    #   - '8085:80'
    volumes:
      - overpass_data:/db
    environment:
      OVERPASS_META: attic
      OVERPASS_MODE: init
      OVERPASS_PLANET_URL: https://s3.amazonaws.com/planet.openhistoricalmap.org/planet/planet-260210_0334.osm.pbf
      OVERPASS_DIFF_URL: http://s3.amazonaws.com/planet.openhistoricalmap.org/replication/minute
      OVERPASS_RULES_LOAD: 10
      OVERPASS_PLANET_PREPROCESS: "mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm.pbf"
      OVERPASS_REPLICATION_SEQUENCE_NUMBER: 1796000
      OVERPASS_ALLOW_DUPLICATE_QUERIES: yes
      # Need to overwrite
      BRANCH_NAME: main
      REPO: OpenHistoricalMap/ohm-deploy
      ENVIRONMENT: production
      REMOTE_APP_DIR: /production/overpass
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 30s 
      retries: 3
      start_period: 180m
    networks:
      - ohm_network

networks:
  ohm_network:
    external: true

volumes:
  overpass_data:
    driver: local
    name: overpass_db_11_02_2026_v4

