services:
  overpass:
    image: ghcr.io/osm-seed/overpass-api:0.1.0-0.dev.git.989.h5488a16
    container_name: overpass
    # ports:
    #   - '8085:80'
    volumes:
      - overpass_data:/db
    environment:
      OVERPASS_META: attic
      OVERPASS_MODE: init
      OVERPASS_PLANET_URL: https://s3.amazonaws.com/planet.openhistoricalmap.org/planet/planet-260216_0301.osm.pbf
      OVERPASS_DIFF_URL: http://s3.amazonaws.com/planet.openhistoricalmap.org/replication/minute
      OVERPASS_RULES_LOAD: 10
      OVERPASS_REPLICATION_SEQUENCE_NUMBER: 1796000
      OVERPASS_ALLOW_DUPLICATE_QUERIES: yes
    restart: always
    ## Disable healthcheck during initialization phase to prevent premature restarts
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 30s 
      retries: 3
      start_period: 180m
    networks:
      - ohm_network

networks:
  ohm_network:
    external: true

volumes:
  overpass_data:
    driver: local
    name: overpass_db_11_02_2026_v4
