services:
  overpass:
    image: ghcr.io/openhistoricalmap/overpass-api:0.0.1-0.dev.git.3374.hec6fee3c
    container_name: overpass
    # ports:
    #   - '8085:80'
    volumes:
      - overpass_data:/db
    environment:
      OVERPASS_META: attic
      OVERPASS_MODE: init
      OVERPASS_PLANET_URL: https://s3.amazonaws.com/planet.openhistoricalmap.org/planet/full-history/planet-history-260510_0442.osm.pbf
      OVERPASS_DIFF_URL: http://s3.amazonaws.com/planet.openhistoricalmap.org/replication/minute
      OVERPASS_RULES_LOAD: 10
      OVERPASS_REPLICATION_SEQUENCE_NUMBER: 1900000
      OVERPASS_ALLOW_DUPLICATE_QUERIES: no
      OVERPASS_RATE_LIMIT: 2
    restart: always
    ## Disable healthcheck during initialization phase to prevent premature restarts
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 30s 
      retries: 3
      start_period: 180m
    networks:
      - ohm_network

networks:
  ohm_network:
    external: true

volumes:
  overpass_data:
    driver: local
    name: overpass_db_14_05_2026_attic_v1
