name: Build and Publish Nominatim site

on:
  push:
    branches:
      - 'main'
      - 'staging'

jobs:
  nominatim:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Set environment variables - Staging & Nominatim-UI-2
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "NOMINATIM_API=https://nominatim-api.openhistoricalmap.org/" >> $GITHUB_ENV
          echo "NOMINATIM_BUCKET=nominatim-staging.openhistoricalmap.org" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.STAGING_NOMINATIM_CLOUDFRONT_ID }}" >> $GITHUB_ENV

      - name: Set environment variables - Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "NOMINATIM_API=https://nominatim-api.openhistoricalmap.org/" >> $GITHUB_ENV
          echo "NOMINATIM_BUCKET=nominatim.openhistoricalmap.org" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.PRODUCTION_NOMINATIM_CLOUDFRONT_ID }}" >> $GITHUB_ENV

      - name: Checkout nominatim-ui repo (Specific SHA)
        uses: actions/checkout@v4
        with:
          repository: OpenHistoricalMap/nominatim-ui
          ref: c14d033389acedf4dcbaabd9d88e14bc40212279
          fetch-depth: 0

      - name: Install Dependencies with Legacy Peer Deps
        run: |
          npm install --legacy-peer-deps
          npm install rollup-plugin-svelte@latest --save-dev --legacy-peer-deps

      - name: Build nominatim-ui frontend
        run: |
          echo "Nominatim_Config.Nominatim_API_Endpoint = '${NOMINATIM_API}';" >> dist/theme/config.theme.js
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Deploy to S3 and Invalidate CloudFront
        run: |
          aws s3 sync dist/ s3://${NOMINATIM_BUCKET}/
          aws cloudfront create-invalidation --distribution-id=${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
