name: Build and Publish nominatim site
on: push
jobs:
  nominatim:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: Setup git
        run: git config --global user.email "noreply@developmentseed.org" && git config --global user.name "Github Action"
      - name: Set environment variables - Staging
        if: github.ref == 'refs/heads/site/nominatim'
        uses: allenevans/set-env@v2.0.0
        with:
          NOMINATIM_API: 'https://nominatim-staging.openhistoricalmap.org/'
          NOMINATIM_BUCKET: 's3://nominatim-staging.openhistoricalmap.org/'
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}
      - name: Set environment variables - Production
        if: github.ref == 'refs/heads/main'
        uses: allenevans/set-env@v2.0.0
        with:
          NOMINATIM_API: 'https://nominatim.openhistoricalmap.org/'
          NOMINATIM_BUCKET: 's3://nominatim.openhistoricalmap.org/'
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID }}
      - name: Clone and build nominatim-ui
        if: github.ref == 'refs/heads/site/nominatim' || github.ref == 'refs/heads/main'
        run: |
          git clone https://github.com/OpenHistoricalMap/nominatim-ui.git
          echo "Nominatim_Config.Nominatim_API_Endpoint = '${NOMINATIM_API}';" >> nominatim-ui/dist/theme/config.theme.js
          cd nominatim-ui/ && npm install && npm run build
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install aws cli
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Push data to s3 and clean cloudfront cache - Production
        if: github.ref == 'refs/heads/site/nominatim' || github.ref == 'refs/heads/main'
        run: |
          aws s3 sync nominatim-ui/dist ${NOMINATIM_BUCKET}
          aws cloudfront create-invalidation --distribution-id=${CLOUDFRONT_DISTRIBUTION_ID} --paths=/
