name: Build and Publish nominatim site
on: push
jobs:
  nominatim:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 10
    - name: Setup git
      run: git config --global user.email "noreply@developmentseed.org" && git config --global user.name "Github Action"

    - name: Clone and build nominatim-ui
      run: |
       git clone https://github.com/OpenHistoricalMap/nominatim-ui.git
       cd nominatim-ui/ && npm install && npm run build
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install aws cli
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        aws s3 sync nominatim-ui/dist/build s3://nominatim-ui-production/
        aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRIBUTION_ID --paths=/
      env:
        CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
